/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;
/**
 * BusinessLocation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class BusinessLocation {
  @JsonProperty("issueAuthorityLicenceNumber")
  private String issueAuthorityLicenceNumber = null;

  @JsonProperty("issueAuthorityEjariLicenceNumber")
  private String issueAuthorityEjariLicenceNumber = null;

  @JsonProperty("makaniNumber")
  private String makaniNumber = null;

  @JsonProperty("ejariNumber")
  private String ejariNumber = null;

  @JsonProperty("DEWAAccountNumber")
  private String deWAAccountNumber = null;

  @JsonProperty("ejariStartDate")
  private LocalDate ejariStartDate = null;

  @JsonProperty("ejariEndDate")
  private LocalDate ejariEndDate = null;

  @JsonProperty("ownerName")
  private String ownerName = null;

  @JsonProperty("tenantName")
  private String tenantName = null;

  @JsonProperty("contractAmount")
  private BigDecimal contractAmount = null;

  @JsonProperty("area")
  private BigDecimal area = null;

  @JsonProperty("isPrimaryLocation")
  private Boolean isPrimaryLocation = null;

  @JsonProperty("areaZone")
  private Integer areaZone = null;

  @JsonProperty("zoneEnglish")
  private String zoneEnglish = null;

  @JsonProperty("zoneArabic")
  private String zoneArabic = null;

  @JsonProperty("locationCode")
  private Integer locationCode = null;

  @JsonProperty("locationEnglish")
  private String locationEnglish = null;

  @JsonProperty("locationArabic")
  private String locationArabic = null;

  public BusinessLocation issueAuthorityLicenceNumber(String issueAuthorityLicenceNumber) {
    this.issueAuthorityLicenceNumber = issueAuthorityLicenceNumber;
    return this;
  }

   /**
   * Get issueAuthorityLicenceNumber
   * @return issueAuthorityLicenceNumber
  **/
  public String getIssueAuthorityLicenceNumber() {
    return issueAuthorityLicenceNumber;
  }

  public void setIssueAuthorityLicenceNumber(String issueAuthorityLicenceNumber) {
    this.issueAuthorityLicenceNumber = issueAuthorityLicenceNumber;
  }

  public BusinessLocation issueAuthorityEjariLicenceNumber(String issueAuthorityEjariLicenceNumber) {
    this.issueAuthorityEjariLicenceNumber = issueAuthorityEjariLicenceNumber;
    return this;
  }

   /**
   * Get issueAuthorityEjariLicenceNumber
   * @return issueAuthorityEjariLicenceNumber
  **/
  public String getIssueAuthorityEjariLicenceNumber() {
    return issueAuthorityEjariLicenceNumber;
  }

  public void setIssueAuthorityEjariLicenceNumber(String issueAuthorityEjariLicenceNumber) {
    this.issueAuthorityEjariLicenceNumber = issueAuthorityEjariLicenceNumber;
  }

  public BusinessLocation makaniNumber(String makaniNumber) {
    this.makaniNumber = makaniNumber;
    return this;
  }

   /**
   * Get makaniNumber
   * @return makaniNumber
  **/
  public String getMakaniNumber() {
    return makaniNumber;
  }

  public void setMakaniNumber(String makaniNumber) {
    this.makaniNumber = makaniNumber;
  }

  public BusinessLocation ejariNumber(String ejariNumber) {
    this.ejariNumber = ejariNumber;
    return this;
  }

   /**
   * Get ejariNumber
   * @return ejariNumber
  **/
  public String getEjariNumber() {
    return ejariNumber;
  }

  public void setEjariNumber(String ejariNumber) {
    this.ejariNumber = ejariNumber;
  }

  public BusinessLocation deWAAccountNumber(String deWAAccountNumber) {
    this.deWAAccountNumber = deWAAccountNumber;
    return this;
  }

   /**
   * Get deWAAccountNumber
   * @return deWAAccountNumber
  **/
  public String getDeWAAccountNumber() {
    return deWAAccountNumber;
  }

  public void setDeWAAccountNumber(String deWAAccountNumber) {
    this.deWAAccountNumber = deWAAccountNumber;
  }

  public BusinessLocation ejariStartDate(LocalDate ejariStartDate) {
    this.ejariStartDate = ejariStartDate;
    return this;
  }

   /**
   * Get ejariStartDate
   * @return ejariStartDate
  **/
  public LocalDate getEjariStartDate() {
    return ejariStartDate;
  }

  public void setEjariStartDate(LocalDate ejariStartDate) {
    this.ejariStartDate = ejariStartDate;
  }

  public BusinessLocation ejariEndDate(LocalDate ejariEndDate) {
    this.ejariEndDate = ejariEndDate;
    return this;
  }

   /**
   * Get ejariEndDate
   * @return ejariEndDate
  **/
  public LocalDate getEjariEndDate() {
    return ejariEndDate;
  }

  public void setEjariEndDate(LocalDate ejariEndDate) {
    this.ejariEndDate = ejariEndDate;
  }

  public BusinessLocation ownerName(String ownerName) {
    this.ownerName = ownerName;
    return this;
  }

   /**
   * Get ownerName
   * @return ownerName
  **/
  public String getOwnerName() {
    return ownerName;
  }

  public void setOwnerName(String ownerName) {
    this.ownerName = ownerName;
  }

  public BusinessLocation tenantName(String tenantName) {
    this.tenantName = tenantName;
    return this;
  }

   /**
   * Get tenantName
   * @return tenantName
  **/
  public String getTenantName() {
    return tenantName;
  }

  public void setTenantName(String tenantName) {
    this.tenantName = tenantName;
  }

  public BusinessLocation contractAmount(BigDecimal contractAmount) {
    this.contractAmount = contractAmount;
    return this;
  }

   /**
   * Get contractAmount
   * @return contractAmount
  **/
  public BigDecimal getContractAmount() {
    return contractAmount;
  }

  public void setContractAmount(BigDecimal contractAmount) {
    this.contractAmount = contractAmount;
  }

  public BusinessLocation area(BigDecimal area) {
    this.area = area;
    return this;
  }

   /**
   * Get area
   * @return area
  **/
  public BigDecimal getArea() {
    return area;
  }

  public void setArea(BigDecimal area) {
    this.area = area;
  }

  public BusinessLocation isPrimaryLocation(Boolean isPrimaryLocation) {
    this.isPrimaryLocation = isPrimaryLocation;
    return this;
  }

   /**
   * Get isPrimaryLocation
   * @return isPrimaryLocation
  **/
  public Boolean isIsPrimaryLocation() {
    return isPrimaryLocation;
  }

  public void setIsPrimaryLocation(Boolean isPrimaryLocation) {
    this.isPrimaryLocation = isPrimaryLocation;
  }

  public BusinessLocation areaZone(Integer areaZone) {
    this.areaZone = areaZone;
    return this;
  }

   /**
   * Get areaZone
   * @return areaZone
  **/
  public Integer getAreaZone() {
    return areaZone;
  }

  public void setAreaZone(Integer areaZone) {
    this.areaZone = areaZone;
  }

  public BusinessLocation zoneEnglish(String zoneEnglish) {
    this.zoneEnglish = zoneEnglish;
    return this;
  }

   /**
   * Get zoneEnglish
   * @return zoneEnglish
  **/
  public String getZoneEnglish() {
    return zoneEnglish;
  }

  public void setZoneEnglish(String zoneEnglish) {
    this.zoneEnglish = zoneEnglish;
  }

  public BusinessLocation zoneArabic(String zoneArabic) {
    this.zoneArabic = zoneArabic;
    return this;
  }

   /**
   * Get zoneArabic
   * @return zoneArabic
  **/

  public String getZoneArabic() {
    return zoneArabic;
  }

  public void setZoneArabic(String zoneArabic) {
    this.zoneArabic = zoneArabic;
  }

  public BusinessLocation locationCode(Integer locationCode) {
    this.locationCode = locationCode;
    return this;
  }

   /**
   * Get locationCode
   * @return locationCode
  **/

  public Integer getLocationCode() {
    return locationCode;
  }

  public void setLocationCode(Integer locationCode) {
    this.locationCode = locationCode;
  }

  public BusinessLocation locationEnglish(String locationEnglish) {
    this.locationEnglish = locationEnglish;
    return this;
  }

   /**
   * Get locationEnglish
   * @return locationEnglish
  **/

  public String getLocationEnglish() {
    return locationEnglish;
  }

  public void setLocationEnglish(String locationEnglish) {
    this.locationEnglish = locationEnglish;
  }

  public BusinessLocation locationArabic(String locationArabic) {
    this.locationArabic = locationArabic;
    return this;
  }

   /**
   * Get locationArabic
   * @return locationArabic
  **/

  public String getLocationArabic() {
    return locationArabic;
  }

  public void setLocationArabic(String locationArabic) {
    this.locationArabic = locationArabic;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessLocation businessLocation = (BusinessLocation) o;
    return Objects.equals(this.issueAuthorityLicenceNumber, businessLocation.issueAuthorityLicenceNumber) &&
        Objects.equals(this.issueAuthorityEjariLicenceNumber, businessLocation.issueAuthorityEjariLicenceNumber) &&
        Objects.equals(this.makaniNumber, businessLocation.makaniNumber) &&
        Objects.equals(this.ejariNumber, businessLocation.ejariNumber) &&
        Objects.equals(this.deWAAccountNumber, businessLocation.deWAAccountNumber) &&
        Objects.equals(this.ejariStartDate, businessLocation.ejariStartDate) &&
        Objects.equals(this.ejariEndDate, businessLocation.ejariEndDate) &&
        Objects.equals(this.ownerName, businessLocation.ownerName) &&
        Objects.equals(this.tenantName, businessLocation.tenantName) &&
        Objects.equals(this.contractAmount, businessLocation.contractAmount) &&
        Objects.equals(this.area, businessLocation.area) &&
        Objects.equals(this.isPrimaryLocation, businessLocation.isPrimaryLocation) &&
        Objects.equals(this.areaZone, businessLocation.areaZone) &&
        Objects.equals(this.zoneEnglish, businessLocation.zoneEnglish) &&
        Objects.equals(this.zoneArabic, businessLocation.zoneArabic) &&
        Objects.equals(this.locationCode, businessLocation.locationCode) &&
        Objects.equals(this.locationEnglish, businessLocation.locationEnglish) &&
        Objects.equals(this.locationArabic, businessLocation.locationArabic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issueAuthorityLicenceNumber, issueAuthorityEjariLicenceNumber, makaniNumber, ejariNumber, deWAAccountNumber, ejariStartDate, ejariEndDate, ownerName, tenantName, contractAmount, area, isPrimaryLocation, areaZone, zoneEnglish, zoneArabic, locationCode, locationEnglish, locationArabic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessLocation {\n");
    
    sb.append("    issueAuthorityLicenceNumber: ").append(toIndentedString(issueAuthorityLicenceNumber)).append("\n");
    sb.append("    issueAuthorityEjariLicenceNumber: ").append(toIndentedString(issueAuthorityEjariLicenceNumber)).append("\n");
    sb.append("    makaniNumber: ").append(toIndentedString(makaniNumber)).append("\n");
    sb.append("    ejariNumber: ").append(toIndentedString(ejariNumber)).append("\n");
    sb.append("    deWAAccountNumber: ").append(toIndentedString(deWAAccountNumber)).append("\n");
    sb.append("    ejariStartDate: ").append(toIndentedString(ejariStartDate)).append("\n");
    sb.append("    ejariEndDate: ").append(toIndentedString(ejariEndDate)).append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("    tenantName: ").append(toIndentedString(tenantName)).append("\n");
    sb.append("    contractAmount: ").append(toIndentedString(contractAmount)).append("\n");
    sb.append("    area: ").append(toIndentedString(area)).append("\n");
    sb.append("    isPrimaryLocation: ").append(toIndentedString(isPrimaryLocation)).append("\n");
    sb.append("    areaZone: ").append(toIndentedString(areaZone)).append("\n");
    sb.append("    zoneEnglish: ").append(toIndentedString(zoneEnglish)).append("\n");
    sb.append("    zoneArabic: ").append(toIndentedString(zoneArabic)).append("\n");
    sb.append("    locationCode: ").append(toIndentedString(locationCode)).append("\n");
    sb.append("    locationEnglish: ").append(toIndentedString(locationEnglish)).append("\n");
    sb.append("    locationArabic: ").append(toIndentedString(locationArabic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
