/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
/**
 * CommerceRegistryType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class CommerceRegistryType {
  @JsonProperty("companyIssueAuthorityID")
  private String companyIssueAuthorityID = null;

  @JsonProperty("issueAuthorityCommerceRegistryNumber")
  private String issueAuthorityCommerceRegistryNumber = null;

  @JsonProperty("companyDuration")
  private Integer companyDuration = null;

  @JsonProperty("shareType")
  private Integer shareType = null;

  @JsonProperty("shareValue")
  private Double shareValue = null;

  @JsonProperty("numberOfShares")
  private Double numberOfShares = null;

  @JsonProperty("capitalNominatedAmount")
  private Double capitalNominatedAmount = null;

  @JsonProperty("capitalPaidAmount")
  private Double capitalPaidAmount = null;

  @JsonProperty("capitalInvestedInDubai")
  private Double capitalInvestedInDubai = null;

  @JsonProperty("attestationAuthority")
  private Integer attestationAuthority = null;

  @JsonProperty("currency")
  private Integer currency = null;

  @JsonProperty("nationalRegistryNumber")
  private String nationalRegistryNumber = null;

  public CommerceRegistryType companyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
    return this;
  }

   /**
   * Get companyIssueAuthorityID
   * @return companyIssueAuthorityID
  **/

  public String getCompanyIssueAuthorityID() {
    return companyIssueAuthorityID;
  }

  public void setCompanyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
  }

  public CommerceRegistryType issueAuthorityCommerceRegistryNumber(String issueAuthorityCommerceRegistryNumber) {
    this.issueAuthorityCommerceRegistryNumber = issueAuthorityCommerceRegistryNumber;
    return this;
  }

   /**
   * Get issueAuthorityCommerceRegistryNumber
   * @return issueAuthorityCommerceRegistryNumber
  **/

  public String getIssueAuthorityCommerceRegistryNumber() {
    return issueAuthorityCommerceRegistryNumber;
  }

  public void setIssueAuthorityCommerceRegistryNumber(String issueAuthorityCommerceRegistryNumber) {
    this.issueAuthorityCommerceRegistryNumber = issueAuthorityCommerceRegistryNumber;
  }

  public CommerceRegistryType companyDuration(Integer companyDuration) {
    this.companyDuration = companyDuration;
    return this;
  }

   /**
   * Get companyDuration
   * @return companyDuration
  **/

  public Integer getCompanyDuration() {
    return companyDuration;
  }

  public void setCompanyDuration(Integer companyDuration) {
    this.companyDuration = companyDuration;
  }

  public CommerceRegistryType shareType(Integer shareType) {
    this.shareType = shareType;
    return this;
  }

   /**
   * Get shareType
   * @return shareType
  **/

  public Integer getShareType() {
    return shareType;
  }

  public void setShareType(Integer shareType) {
    this.shareType = shareType;
  }

  public CommerceRegistryType shareValue(Double shareValue) {
    this.shareValue = shareValue;
    return this;
  }

   /**
   * Get shareValue
   * @return shareValue
  **/

  public Double getShareValue() {
    return shareValue;
  }

  public void setShareValue(Double shareValue) {
    this.shareValue = shareValue;
  }

  public CommerceRegistryType numberOfShares(Double numberOfShares) {
    this.numberOfShares = numberOfShares;
    return this;
  }

   /**
   * Get numberOfShares
   * @return numberOfShares
  **/

  public Double getNumberOfShares() {
    return numberOfShares;
  }

  public void setNumberOfShares(Double numberOfShares) {
    this.numberOfShares = numberOfShares;
  }

  public CommerceRegistryType capitalNominatedAmount(Double capitalNominatedAmount) {
    this.capitalNominatedAmount = capitalNominatedAmount;
    return this;
  }

   /**
   * Get capitalNominatedAmount
   * @return capitalNominatedAmount
  **/

  public Double getCapitalNominatedAmount() {
    return capitalNominatedAmount;
  }

  public void setCapitalNominatedAmount(Double capitalNominatedAmount) {
    this.capitalNominatedAmount = capitalNominatedAmount;
  }

  public CommerceRegistryType capitalPaidAmount(Double capitalPaidAmount) {
    this.capitalPaidAmount = capitalPaidAmount;
    return this;
  }

   /**
   * Get capitalPaidAmount
   * @return capitalPaidAmount
  **/

  public Double getCapitalPaidAmount() {
    return capitalPaidAmount;
  }

  public void setCapitalPaidAmount(Double capitalPaidAmount) {
    this.capitalPaidAmount = capitalPaidAmount;
  }

  public CommerceRegistryType capitalInvestedInDubai(Double capitalInvestedInDubai) {
    this.capitalInvestedInDubai = capitalInvestedInDubai;
    return this;
  }

   /**
   * Get capitalInvestedInDubai
   * @return capitalInvestedInDubai
  **/

  public Double getCapitalInvestedInDubai() {
    return capitalInvestedInDubai;
  }

  public void setCapitalInvestedInDubai(Double capitalInvestedInDubai) {
    this.capitalInvestedInDubai = capitalInvestedInDubai;
  }

  public CommerceRegistryType attestationAuthority(Integer attestationAuthority) {
    this.attestationAuthority = attestationAuthority;
    return this;
  }

   /**
   * Get attestationAuthority
   * @return attestationAuthority
  **/

  public Integer getAttestationAuthority() {
    return attestationAuthority;
  }

  public void setAttestationAuthority(Integer attestationAuthority) {
    this.attestationAuthority = attestationAuthority;
  }

  public CommerceRegistryType currency(Integer currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/

  public Integer getCurrency() {
    return currency;
  }

  public void setCurrency(Integer currency) {
    this.currency = currency;
  }

  public CommerceRegistryType nationalRegistryNumber(String nationalRegistryNumber) {
    this.nationalRegistryNumber = nationalRegistryNumber;
    return this;
  }

   /**
   * Get nationalRegistryNumber
   * @return nationalRegistryNumber
  **/

  public String getNationalRegistryNumber() {
    return nationalRegistryNumber;
  }

  public void setNationalRegistryNumber(String nationalRegistryNumber) {
    this.nationalRegistryNumber = nationalRegistryNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommerceRegistryType commerceRegistryType = (CommerceRegistryType) o;
    return Objects.equals(this.companyIssueAuthorityID, commerceRegistryType.companyIssueAuthorityID) &&
        Objects.equals(this.issueAuthorityCommerceRegistryNumber, commerceRegistryType.issueAuthorityCommerceRegistryNumber) &&
        Objects.equals(this.companyDuration, commerceRegistryType.companyDuration) &&
        Objects.equals(this.shareType, commerceRegistryType.shareType) &&
        Objects.equals(this.shareValue, commerceRegistryType.shareValue) &&
        Objects.equals(this.numberOfShares, commerceRegistryType.numberOfShares) &&
        Objects.equals(this.capitalNominatedAmount, commerceRegistryType.capitalNominatedAmount) &&
        Objects.equals(this.capitalPaidAmount, commerceRegistryType.capitalPaidAmount) &&
        Objects.equals(this.capitalInvestedInDubai, commerceRegistryType.capitalInvestedInDubai) &&
        Objects.equals(this.attestationAuthority, commerceRegistryType.attestationAuthority) &&
        Objects.equals(this.currency, commerceRegistryType.currency) &&
        Objects.equals(this.nationalRegistryNumber, commerceRegistryType.nationalRegistryNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyIssueAuthorityID, issueAuthorityCommerceRegistryNumber, companyDuration, shareType, shareValue, numberOfShares, capitalNominatedAmount, capitalPaidAmount, capitalInvestedInDubai, attestationAuthority, currency, nationalRegistryNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommerceRegistryType {\n");
    
    sb.append("    companyIssueAuthorityID: ").append(toIndentedString(companyIssueAuthorityID)).append("\n");
    sb.append("    issueAuthorityCommerceRegistryNumber: ").append(toIndentedString(issueAuthorityCommerceRegistryNumber)).append("\n");
    sb.append("    companyDuration: ").append(toIndentedString(companyDuration)).append("\n");
    sb.append("    shareType: ").append(toIndentedString(shareType)).append("\n");
    sb.append("    shareValue: ").append(toIndentedString(shareValue)).append("\n");
    sb.append("    numberOfShares: ").append(toIndentedString(numberOfShares)).append("\n");
    sb.append("    capitalNominatedAmount: ").append(toIndentedString(capitalNominatedAmount)).append("\n");
    sb.append("    capitalPaidAmount: ").append(toIndentedString(capitalPaidAmount)).append("\n");
    sb.append("    capitalInvestedInDubai: ").append(toIndentedString(capitalInvestedInDubai)).append("\n");
    sb.append("    attestationAuthority: ").append(toIndentedString(attestationAuthority)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    nationalRegistryNumber: ").append(toIndentedString(nationalRegistryNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
