/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Objects;
/**
 * CompanyType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class CompanyType {
  @JsonProperty("companyIssueAuthorityID")
  private String companyIssueAuthorityID = null;

  @JsonProperty("arabicName")
  private String arabicName = null;

  @JsonProperty("englishName")
  private String englishName = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("mobile")
  private String mobile = null;

  @JsonProperty("nationality")
  private String nationality = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("legalType")
  private Integer legalType = null;

  @JsonProperty("issueDate")
  private LocalDate issueDate = null;

  @JsonProperty("expiryDate")
  private LocalDate expiryDate = null;

  @JsonProperty("cancellationDate")
  private LocalDate cancellationDate = null;

  @JsonProperty("originLicenceNumber")
  private String originLicenceNumber = null;

  @JsonProperty("isMobileVerified")
  private Boolean isMobileVerified = null;

  @JsonProperty("mobileVerificationDate")
  private OffsetDateTime mobileVerificationDate = null;

  @JsonProperty("mobileVerificationChannel")
  private Integer mobileVerificationChannel = null;

  @JsonProperty("isEmailVerified")
  private Boolean isEmailVerified = null;

  @JsonProperty("emailVerificationDate")
  private OffsetDateTime emailVerificationDate = null;

  @JsonProperty("emailVerificationChannel")
  private Integer emailVerificationChannel = null;

  @JsonProperty("isScreened")
  private Boolean isScreened = null;

  @JsonProperty("screeningDate")
  private OffsetDateTime screeningDate = null;

  @JsonProperty("screeningChannel")
  private Integer screeningChannel = null;

  @JsonProperty("hasDiscrepancy")
  private Boolean hasDiscrepancy = null;

  @JsonProperty("hasUBOExemption")
  private Boolean hasUBOExemption = null;

  public CompanyType companyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
    return this;
  }

   /**
   * Get companyIssueAuthorityID
   * @return companyIssueAuthorityID
  **/

  public String getCompanyIssueAuthorityID() {
    return companyIssueAuthorityID;
  }

  public void setCompanyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
  }

  public CompanyType arabicName(String arabicName) {
    this.arabicName = arabicName;
    return this;
  }

   /**
   * Get arabicName
   * @return arabicName
  **/

  public String getArabicName() {
    return arabicName;
  }

  public void setArabicName(String arabicName) {
    this.arabicName = arabicName;
  }

  public CompanyType englishName(String englishName) {
    this.englishName = englishName;
    return this;
  }

   /**
   * Get englishName
   * @return englishName
  **/

  public String getEnglishName() {
    return englishName;
  }

  public void setEnglishName(String englishName) {
    this.englishName = englishName;
  }

  public CompanyType email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public CompanyType mobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Get mobile
   * @return mobile
  **/

  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public CompanyType nationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

   /**
   * Get nationality
   * @return nationality
  **/

  public String getNationality() {
    return nationality;
  }

  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  public CompanyType status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/

  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public CompanyType legalType(Integer legalType) {
    this.legalType = legalType;
    return this;
  }

   /**
   * Get legalType
   * @return legalType
  **/

  public Integer getLegalType() {
    return legalType;
  }

  public void setLegalType(Integer legalType) {
    this.legalType = legalType;
  }

  public CompanyType issueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
    return this;
  }

   /**
   * Get issueDate
   * @return issueDate
  **/

  public LocalDate getIssueDate() {
    return issueDate;
  }

  public void setIssueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
  }

  public CompanyType expiryDate(LocalDate expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/

  public LocalDate getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(LocalDate expiryDate) {
    this.expiryDate = expiryDate;
  }

  public CompanyType cancellationDate(LocalDate cancellationDate) {
    this.cancellationDate = cancellationDate;
    return this;
  }

   /**
   * Get cancellationDate
   * @return cancellationDate
  **/

  public LocalDate getCancellationDate() {
    return cancellationDate;
  }

  public void setCancellationDate(LocalDate cancellationDate) {
    this.cancellationDate = cancellationDate;
  }

  public CompanyType originLicenceNumber(String originLicenceNumber) {
    this.originLicenceNumber = originLicenceNumber;
    return this;
  }

   /**
   * Get originLicenceNumber
   * @return originLicenceNumber
  **/

  public String getOriginLicenceNumber() {
    return originLicenceNumber;
  }

  public void setOriginLicenceNumber(String originLicenceNumber) {
    this.originLicenceNumber = originLicenceNumber;
  }

  public CompanyType isMobileVerified(Boolean isMobileVerified) {
    this.isMobileVerified = isMobileVerified;
    return this;
  }

   /**
   * Get isMobileVerified
   * @return isMobileVerified
  **/

  public Boolean isIsMobileVerified() {
    return isMobileVerified;
  }

  public void setIsMobileVerified(Boolean isMobileVerified) {
    this.isMobileVerified = isMobileVerified;
  }

  public CompanyType mobileVerificationDate(OffsetDateTime mobileVerificationDate) {
    this.mobileVerificationDate = mobileVerificationDate;
    return this;
  }

   /**
   * Get mobileVerificationDate
   * @return mobileVerificationDate
  **/

  public OffsetDateTime getMobileVerificationDate() {
    return mobileVerificationDate;
  }

  public void setMobileVerificationDate(OffsetDateTime mobileVerificationDate) {
    this.mobileVerificationDate = mobileVerificationDate;
  }

  public CompanyType mobileVerificationChannel(Integer mobileVerificationChannel) {
    this.mobileVerificationChannel = mobileVerificationChannel;
    return this;
  }

   /**
   * Get mobileVerificationChannel
   * @return mobileVerificationChannel
  **/

  public Integer getMobileVerificationChannel() {
    return mobileVerificationChannel;
  }

  public void setMobileVerificationChannel(Integer mobileVerificationChannel) {
    this.mobileVerificationChannel = mobileVerificationChannel;
  }

  public CompanyType isEmailVerified(Boolean isEmailVerified) {
    this.isEmailVerified = isEmailVerified;
    return this;
  }

   /**
   * Get isEmailVerified
   * @return isEmailVerified
  **/

  public Boolean isIsEmailVerified() {
    return isEmailVerified;
  }

  public void setIsEmailVerified(Boolean isEmailVerified) {
    this.isEmailVerified = isEmailVerified;
  }

  public CompanyType emailVerificationDate(OffsetDateTime emailVerificationDate) {
    this.emailVerificationDate = emailVerificationDate;
    return this;
  }

   /**
   * Get emailVerificationDate
   * @return emailVerificationDate
  **/

  public OffsetDateTime getEmailVerificationDate() {
    return emailVerificationDate;
  }

  public void setEmailVerificationDate(OffsetDateTime emailVerificationDate) {
    this.emailVerificationDate = emailVerificationDate;
  }

  public CompanyType emailVerificationChannel(Integer emailVerificationChannel) {
    this.emailVerificationChannel = emailVerificationChannel;
    return this;
  }

   /**
   * Get emailVerificationChannel
   * @return emailVerificationChannel
  **/

  public Integer getEmailVerificationChannel() {
    return emailVerificationChannel;
  }

  public void setEmailVerificationChannel(Integer emailVerificationChannel) {
    this.emailVerificationChannel = emailVerificationChannel;
  }

  public CompanyType isScreened(Boolean isScreened) {
    this.isScreened = isScreened;
    return this;
  }

   /**
   * Get isScreened
   * @return isScreened
  **/

  public Boolean isIsScreened() {
    return isScreened;
  }

  public void setIsScreened(Boolean isScreened) {
    this.isScreened = isScreened;
  }

  public CompanyType screeningDate(OffsetDateTime screeningDate) {
    this.screeningDate = screeningDate;
    return this;
  }

   /**
   * Get screeningDate
   * @return screeningDate
  **/

  public OffsetDateTime getScreeningDate() {
    return screeningDate;
  }

  public void setScreeningDate(OffsetDateTime screeningDate) {
    this.screeningDate = screeningDate;
  }

  public CompanyType screeningChannel(Integer screeningChannel) {
    this.screeningChannel = screeningChannel;
    return this;
  }

   /**
   * Get screeningChannel
   * @return screeningChannel
  **/

  public Integer getScreeningChannel() {
    return screeningChannel;
  }

  public void setScreeningChannel(Integer screeningChannel) {
    this.screeningChannel = screeningChannel;
  }

  public CompanyType hasDiscrepancy(Boolean hasDiscrepancy) {
    this.hasDiscrepancy = hasDiscrepancy;
    return this;
  }

   /**
   * Get hasDiscrepancy
   * @return hasDiscrepancy
  **/

  public Boolean isHasDiscrepancy() {
    return hasDiscrepancy;
  }

  public void setHasDiscrepancy(Boolean hasDiscrepancy) {
    this.hasDiscrepancy = hasDiscrepancy;
  }

  public CompanyType hasUBOExemption(Boolean hasUBOExemption) {
    this.hasUBOExemption = hasUBOExemption;
    return this;
  }

   /**
   * Get hasUBOExemption
   * @return hasUBOExemption
  **/

  public Boolean isHasUBOExemption() {
    return hasUBOExemption;
  }

  public void setHasUBOExemption(Boolean hasUBOExemption) {
    this.hasUBOExemption = hasUBOExemption;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyType companyType = (CompanyType) o;
    return Objects.equals(this.companyIssueAuthorityID, companyType.companyIssueAuthorityID) &&
        Objects.equals(this.arabicName, companyType.arabicName) &&
        Objects.equals(this.englishName, companyType.englishName) &&
        Objects.equals(this.email, companyType.email) &&
        Objects.equals(this.mobile, companyType.mobile) &&
        Objects.equals(this.nationality, companyType.nationality) &&
        Objects.equals(this.status, companyType.status) &&
        Objects.equals(this.legalType, companyType.legalType) &&
        Objects.equals(this.issueDate, companyType.issueDate) &&
        Objects.equals(this.expiryDate, companyType.expiryDate) &&
        Objects.equals(this.cancellationDate, companyType.cancellationDate) &&
        Objects.equals(this.originLicenceNumber, companyType.originLicenceNumber) &&
        Objects.equals(this.isMobileVerified, companyType.isMobileVerified) &&
        Objects.equals(this.mobileVerificationDate, companyType.mobileVerificationDate) &&
        Objects.equals(this.mobileVerificationChannel, companyType.mobileVerificationChannel) &&
        Objects.equals(this.isEmailVerified, companyType.isEmailVerified) &&
        Objects.equals(this.emailVerificationDate, companyType.emailVerificationDate) &&
        Objects.equals(this.emailVerificationChannel, companyType.emailVerificationChannel) &&
        Objects.equals(this.isScreened, companyType.isScreened) &&
        Objects.equals(this.screeningDate, companyType.screeningDate) &&
        Objects.equals(this.screeningChannel, companyType.screeningChannel) &&
        Objects.equals(this.hasDiscrepancy, companyType.hasDiscrepancy) &&
        Objects.equals(this.hasUBOExemption, companyType.hasUBOExemption);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyIssueAuthorityID, arabicName, englishName, email, mobile, nationality, status, legalType, issueDate, expiryDate, cancellationDate, originLicenceNumber, isMobileVerified, mobileVerificationDate, mobileVerificationChannel, isEmailVerified, emailVerificationDate, emailVerificationChannel, isScreened, screeningDate, screeningChannel, hasDiscrepancy, hasUBOExemption);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyType {\n");
    
    sb.append("    companyIssueAuthorityID: ").append(toIndentedString(companyIssueAuthorityID)).append("\n");
    sb.append("    arabicName: ").append(toIndentedString(arabicName)).append("\n");
    sb.append("    englishName: ").append(toIndentedString(englishName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    legalType: ").append(toIndentedString(legalType)).append("\n");
    sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    cancellationDate: ").append(toIndentedString(cancellationDate)).append("\n");
    sb.append("    originLicenceNumber: ").append(toIndentedString(originLicenceNumber)).append("\n");
    sb.append("    isMobileVerified: ").append(toIndentedString(isMobileVerified)).append("\n");
    sb.append("    mobileVerificationDate: ").append(toIndentedString(mobileVerificationDate)).append("\n");
    sb.append("    mobileVerificationChannel: ").append(toIndentedString(mobileVerificationChannel)).append("\n");
    sb.append("    isEmailVerified: ").append(toIndentedString(isEmailVerified)).append("\n");
    sb.append("    emailVerificationDate: ").append(toIndentedString(emailVerificationDate)).append("\n");
    sb.append("    emailVerificationChannel: ").append(toIndentedString(emailVerificationChannel)).append("\n");
    sb.append("    isScreened: ").append(toIndentedString(isScreened)).append("\n");
    sb.append("    screeningDate: ").append(toIndentedString(screeningDate)).append("\n");
    sb.append("    screeningChannel: ").append(toIndentedString(screeningChannel)).append("\n");
    sb.append("    hasDiscrepancy: ").append(toIndentedString(hasDiscrepancy)).append("\n");
    sb.append("    hasUBOExemption: ").append(toIndentedString(hasUBOExemption)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
