/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * DIMPerson
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class DIMPerson {
  @JsonProperty("person")
  private PersonType person = null;

  @JsonProperty("address")
  private PersonAddressType address = null;

  @JsonProperty("documents")
  private List<Documents> documents = null;

  public DIMPerson person(PersonType person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public PersonType getPerson() {
    return person;
  }

  public void setPerson(PersonType person) {
    this.person = person;
  }

  public DIMPerson address(PersonAddressType address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public PersonAddressType getAddress() {
    return address;
  }

  public void setAddress(PersonAddressType address) {
    this.address = address;
  }

  public DIMPerson documents(List<Documents> documents) {
    this.documents = documents;
    return this;
  }

  public DIMPerson addDocumentsItem(Documents documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<>();
    }
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Get documents
   * @return documents
  **/
  public List<Documents> getDocuments() {
    return documents;
  }

  public void setDocuments(List<Documents> documents) {
    this.documents = documents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DIMPerson diMPerson = (DIMPerson) o;
    return Objects.equals(this.person, diMPerson.person) &&
        Objects.equals(this.address, diMPerson.address) &&
        Objects.equals(this.documents, diMPerson.documents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, address, documents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DIMPerson {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
