/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.OffsetDateTime;
import java.util.Objects;
/**
 * Documents
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class Documents {
  @JsonProperty("legalEntity")
  private LegalEntityType legalEntity = null;

  @JsonProperty("issueAuthorityLicenceNumber")
  private String issueAuthorityLicenceNumber = null;

  @JsonProperty("issueAuthorityTradeNameNumber")
  private String issueAuthorityTradeNameNumber = null;

  @JsonProperty("type")
  private Integer type = null;

  @JsonProperty("uploadDate")
  private OffsetDateTime uploadDate = null;

  @JsonProperty("issueAuthorityReference")
  private String issueAuthorityReference = null;

  @JsonProperty("issueAuthorityTransaction")
  private String issueAuthorityTransaction = null;

  @JsonProperty("MIMEType")
  private Integer miMEType = null;

  public Documents legalEntity(LegalEntityType legalEntity) {
    this.legalEntity = legalEntity;
    return this;
  }

   /**
   * Get legalEntity
   * @return legalEntity
  **/

  public LegalEntityType getLegalEntity() {
    return legalEntity;
  }

  public void setLegalEntity(LegalEntityType legalEntity) {
    this.legalEntity = legalEntity;
  }

  public Documents issueAuthorityLicenceNumber(String issueAuthorityLicenceNumber) {
    this.issueAuthorityLicenceNumber = issueAuthorityLicenceNumber;
    return this;
  }

   /**
   * Get issueAuthorityLicenceNumber
   * @return issueAuthorityLicenceNumber
  **/

  public String getIssueAuthorityLicenceNumber() {
    return issueAuthorityLicenceNumber;
  }

  public void setIssueAuthorityLicenceNumber(String issueAuthorityLicenceNumber) {
    this.issueAuthorityLicenceNumber = issueAuthorityLicenceNumber;
  }

  public Documents issueAuthorityTradeNameNumber(String issueAuthorityTradeNameNumber) {
    this.issueAuthorityTradeNameNumber = issueAuthorityTradeNameNumber;
    return this;
  }

   /**
   * Get issueAuthorityTradeNameNumber
   * @return issueAuthorityTradeNameNumber
  **/

  public String getIssueAuthorityTradeNameNumber() {
    return issueAuthorityTradeNameNumber;
  }

  public void setIssueAuthorityTradeNameNumber(String issueAuthorityTradeNameNumber) {
    this.issueAuthorityTradeNameNumber = issueAuthorityTradeNameNumber;
  }

  public Documents type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/

  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public Documents uploadDate(OffsetDateTime uploadDate) {
    this.uploadDate = uploadDate;
    return this;
  }

   /**
   * Get uploadDate
   * @return uploadDate
  **/

  public OffsetDateTime getUploadDate() {
    return uploadDate;
  }

  public void setUploadDate(OffsetDateTime uploadDate) {
    this.uploadDate = uploadDate;
  }

  public Documents issueAuthorityReference(String issueAuthorityReference) {
    this.issueAuthorityReference = issueAuthorityReference;
    return this;
  }

   /**
   * Get issueAuthorityReference
   * @return issueAuthorityReference
  **/

  public String getIssueAuthorityReference() {
    return issueAuthorityReference;
  }

  public void setIssueAuthorityReference(String issueAuthorityReference) {
    this.issueAuthorityReference = issueAuthorityReference;
  }

  public Documents issueAuthorityTransaction(String issueAuthorityTransaction) {
    this.issueAuthorityTransaction = issueAuthorityTransaction;
    return this;
  }

   /**
   * Get issueAuthorityTransaction
   * @return issueAuthorityTransaction
  **/

  public String getIssueAuthorityTransaction() {
    return issueAuthorityTransaction;
  }

  public void setIssueAuthorityTransaction(String issueAuthorityTransaction) {
    this.issueAuthorityTransaction = issueAuthorityTransaction;
  }

  public Documents miMEType(Integer miMEType) {
    this.miMEType = miMEType;
    return this;
  }

   /**
   * Get miMEType
   * @return miMEType
  **/

  public Integer getMiMEType() {
    return miMEType;
  }

  public void setMiMEType(Integer miMEType) {
    this.miMEType = miMEType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Documents documents = (Documents) o;
    return Objects.equals(this.legalEntity, documents.legalEntity) &&
        Objects.equals(this.issueAuthorityLicenceNumber, documents.issueAuthorityLicenceNumber) &&
        Objects.equals(this.issueAuthorityTradeNameNumber, documents.issueAuthorityTradeNameNumber) &&
        Objects.equals(this.type, documents.type) &&
        Objects.equals(this.uploadDate, documents.uploadDate) &&
        Objects.equals(this.issueAuthorityReference, documents.issueAuthorityReference) &&
        Objects.equals(this.issueAuthorityTransaction, documents.issueAuthorityTransaction) &&
        Objects.equals(this.miMEType, documents.miMEType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(legalEntity, issueAuthorityLicenceNumber, issueAuthorityTradeNameNumber, type, uploadDate, issueAuthorityReference, issueAuthorityTransaction, miMEType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Documents {\n");
    
    sb.append("    legalEntity: ").append(toIndentedString(legalEntity)).append("\n");
    sb.append("    issueAuthorityLicenceNumber: ").append(toIndentedString(issueAuthorityLicenceNumber)).append("\n");
    sb.append("    issueAuthorityTradeNameNumber: ").append(toIndentedString(issueAuthorityTradeNameNumber)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    uploadDate: ").append(toIndentedString(uploadDate)).append("\n");
    sb.append("    issueAuthorityReference: ").append(toIndentedString(issueAuthorityReference)).append("\n");
    sb.append("    issueAuthorityTransaction: ").append(toIndentedString(issueAuthorityTransaction)).append("\n");
    sb.append("    miMEType: ").append(toIndentedString(miMEType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
