/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.util.Objects;
/**
 * LegalEntityAssociationType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class LegalEntityAssociationType {
  @JsonProperty("legalEntity")
  private LegalEntityType legalEntity = null;

  @JsonProperty("associatedLegalEntity")
  private LegalEntityType associatedLegalEntity = null;

  @JsonProperty("associationType")
  private Integer associationType = null;

  @JsonProperty("startDate")
  private LocalDate startDate = null;

  @JsonProperty("expiryDate")
  private LocalDate expiryDate = null;

  @JsonProperty("cancellationDate")
  private LocalDate cancellationDate = null;

  @JsonProperty("status")
  private Integer status = null;

  public LegalEntityAssociationType legalEntity(LegalEntityType legalEntity) {
    this.legalEntity = legalEntity;
    return this;
  }

   /**
   * Get legalEntity
   * @return legalEntity
  **/

  public LegalEntityType getLegalEntity() {
    return legalEntity;
  }

  public void setLegalEntity(LegalEntityType legalEntity) {
    this.legalEntity = legalEntity;
  }

  public LegalEntityAssociationType associatedLegalEntity(LegalEntityType associatedLegalEntity) {
    this.associatedLegalEntity = associatedLegalEntity;
    return this;
  }

   /**
   * Get associatedLegalEntity
   * @return associatedLegalEntity
  **/

  public LegalEntityType getAssociatedLegalEntity() {
    return associatedLegalEntity;
  }

  public void setAssociatedLegalEntity(LegalEntityType associatedLegalEntity) {
    this.associatedLegalEntity = associatedLegalEntity;
  }

  public LegalEntityAssociationType associationType(Integer associationType) {
    this.associationType = associationType;
    return this;
  }

   /**
   * Get associationType
   * @return associationType
  **/

  public Integer getAssociationType() {
    return associationType;
  }

  public void setAssociationType(Integer associationType) {
    this.associationType = associationType;
  }

  public LegalEntityAssociationType startDate(LocalDate startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/

  public LocalDate getStartDate() {
    return startDate;
  }

  public void setStartDate(LocalDate startDate) {
    this.startDate = startDate;
  }

  public LegalEntityAssociationType expiryDate(LocalDate expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/

  public LocalDate getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(LocalDate expiryDate) {
    this.expiryDate = expiryDate;
  }

  public LegalEntityAssociationType cancellationDate(LocalDate cancellationDate) {
    this.cancellationDate = cancellationDate;
    return this;
  }

   /**
   * Get cancellationDate
   * @return cancellationDate
  **/

  public LocalDate getCancellationDate() {
    return cancellationDate;
  }

  public void setCancellationDate(LocalDate cancellationDate) {
    this.cancellationDate = cancellationDate;
  }

  public LegalEntityAssociationType status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/

  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegalEntityAssociationType legalEntityAssociationType = (LegalEntityAssociationType) o;
    return Objects.equals(this.legalEntity, legalEntityAssociationType.legalEntity) &&
        Objects.equals(this.associatedLegalEntity, legalEntityAssociationType.associatedLegalEntity) &&
        Objects.equals(this.associationType, legalEntityAssociationType.associationType) &&
        Objects.equals(this.startDate, legalEntityAssociationType.startDate) &&
        Objects.equals(this.expiryDate, legalEntityAssociationType.expiryDate) &&
        Objects.equals(this.cancellationDate, legalEntityAssociationType.cancellationDate) &&
        Objects.equals(this.status, legalEntityAssociationType.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(legalEntity, associatedLegalEntity, associationType, startDate, expiryDate, cancellationDate, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegalEntityAssociationType {\n");
    
    sb.append("    legalEntity: ").append(toIndentedString(legalEntity)).append("\n");
    sb.append("    associatedLegalEntity: ").append(toIndentedString(associatedLegalEntity)).append("\n");
    sb.append("    associationType: ").append(toIndentedString(associationType)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    cancellationDate: ").append(toIndentedString(cancellationDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
