/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
/**
 * LegalEntityType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class LegalEntityType {
  @JsonProperty("companyIssueAuthorityID")
  private String companyIssueAuthorityID = null;

  @JsonProperty("personIssueAuthorityID")
  private String personIssueAuthorityID = null;

  public LegalEntityType companyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
    return this;
  }

   /**
   * Get companyIssueAuthorityID
   * @return companyIssueAuthorityID
  **/

  public String getCompanyIssueAuthorityID() {
    return companyIssueAuthorityID;
  }

  public void setCompanyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
  }

  public LegalEntityType personIssueAuthorityID(String personIssueAuthorityID) {
    this.personIssueAuthorityID = personIssueAuthorityID;
    return this;
  }

   /**
   * Get personIssueAuthorityID
   * @return personIssueAuthorityID
  **/

  public String getPersonIssueAuthorityID() {
    return personIssueAuthorityID;
  }

  public void setPersonIssueAuthorityID(String personIssueAuthorityID) {
    this.personIssueAuthorityID = personIssueAuthorityID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegalEntityType legalEntityType = (LegalEntityType) o;
    return Objects.equals(this.companyIssueAuthorityID, legalEntityType.companyIssueAuthorityID) &&
        Objects.equals(this.personIssueAuthorityID, legalEntityType.personIssueAuthorityID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyIssueAuthorityID, personIssueAuthorityID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegalEntityType {\n");
    
    sb.append("    companyIssueAuthorityID: ").append(toIndentedString(companyIssueAuthorityID)).append("\n");
    sb.append("    personIssueAuthorityID: ").append(toIndentedString(personIssueAuthorityID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
