/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * LegalContract
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class LegalContract {
  @JsonProperty("companyIssueAuthorityID")
  private String companyIssueAuthorityID = null;

  @JsonProperty("issueAuthorityContractNumber")
  private String issueAuthorityContractNumber = null;

  @JsonProperty("companyDuration")
  private Integer companyDuration = null;

  @JsonProperty("numberOfShares")
  private Integer numberOfShares = null;

  @JsonProperty("shareValue")
  private BigDecimal shareValue = null;

  @JsonProperty("capital")
  private BigDecimal capital = null;

  @JsonProperty("directorTenure")
  private Integer directorTenure = null;

  @JsonProperty("issueDate")
  private LocalDate issueDate = null;

  @JsonProperty("contractType")
  private Integer contractType = null;

  @JsonProperty("personAuthorities")
  private List<PersonAuthorities> personAuthorities = null;

  public LegalContract companyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
    return this;
  }

   /**
   * Get companyIssueAuthorityID
   * @return companyIssueAuthorityID
  **/

  public String getCompanyIssueAuthorityID() {
    return companyIssueAuthorityID;
  }

  public void setCompanyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
  }

  public LegalContract issueAuthorityContractNumber(String issueAuthorityContractNumber) {
    this.issueAuthorityContractNumber = issueAuthorityContractNumber;
    return this;
  }

   /**
   * Get issueAuthorityContractNumber
   * @return issueAuthorityContractNumber
  **/

  public String getIssueAuthorityContractNumber() {
    return issueAuthorityContractNumber;
  }

  public void setIssueAuthorityContractNumber(String issueAuthorityContractNumber) {
    this.issueAuthorityContractNumber = issueAuthorityContractNumber;
  }

  public LegalContract companyDuration(Integer companyDuration) {
    this.companyDuration = companyDuration;
    return this;
  }

   /**
   * Get companyDuration
   * @return companyDuration
  **/

  public Integer getCompanyDuration() {
    return companyDuration;
  }

  public void setCompanyDuration(Integer companyDuration) {
    this.companyDuration = companyDuration;
  }

  public LegalContract numberOfShares(Integer numberOfShares) {
    this.numberOfShares = numberOfShares;
    return this;
  }

   /**
   * Get numberOfShares
   * @return numberOfShares
  **/

  public Integer getNumberOfShares() {
    return numberOfShares;
  }

  public void setNumberOfShares(Integer numberOfShares) {
    this.numberOfShares = numberOfShares;
  }

  public LegalContract shareValue(BigDecimal shareValue) {
    this.shareValue = shareValue;
    return this;
  }

   /**
   * Get shareValue
   * @return shareValue
  **/

  public BigDecimal getShareValue() {
    return shareValue;
  }

  public void setShareValue(BigDecimal shareValue) {
    this.shareValue = shareValue;
  }

  public LegalContract capital(BigDecimal capital) {
    this.capital = capital;
    return this;
  }

   /**
   * Get capital
   * @return capital
  **/

  public BigDecimal getCapital() {
    return capital;
  }

  public void setCapital(BigDecimal capital) {
    this.capital = capital;
  }

  public LegalContract directorTenure(Integer directorTenure) {
    this.directorTenure = directorTenure;
    return this;
  }

   /**
   * Get directorTenure
   * @return directorTenure
  **/

  public Integer getDirectorTenure() {
    return directorTenure;
  }

  public void setDirectorTenure(Integer directorTenure) {
    this.directorTenure = directorTenure;
  }

  public LegalContract issueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
    return this;
  }

   /**
   * Get issueDate
   * @return issueDate
  **/

  public LocalDate getIssueDate() {
    return issueDate;
  }

  public void setIssueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
  }

  public LegalContract contractType(Integer contractType) {
    this.contractType = contractType;
    return this;
  }

   /**
   * Get contractType
   * @return contractType
  **/

  public Integer getContractType() {
    return contractType;
  }

  public void setContractType(Integer contractType) {
    this.contractType = contractType;
  }

  public LegalContract personAuthorities(List<PersonAuthorities> personAuthorities) {
    this.personAuthorities = personAuthorities;
    return this;
  }

  public LegalContract addPersonAuthoritiesItem(PersonAuthorities personAuthoritiesItem) {
    if (this.personAuthorities == null) {
      this.personAuthorities = new ArrayList<>();
    }
    this.personAuthorities.add(personAuthoritiesItem);
    return this;
  }

   /**
   * Get personAuthorities
   * @return personAuthorities
  **/

  public List<PersonAuthorities> getPersonAuthorities() {
    return personAuthorities;
  }

  public void setPersonAuthorities(List<PersonAuthorities> personAuthorities) {
    this.personAuthorities = personAuthorities;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegalContract legalContract = (LegalContract) o;
    return Objects.equals(this.companyIssueAuthorityID, legalContract.companyIssueAuthorityID) &&
        Objects.equals(this.issueAuthorityContractNumber, legalContract.issueAuthorityContractNumber) &&
        Objects.equals(this.companyDuration, legalContract.companyDuration) &&
        Objects.equals(this.numberOfShares, legalContract.numberOfShares) &&
        Objects.equals(this.shareValue, legalContract.shareValue) &&
        Objects.equals(this.capital, legalContract.capital) &&
        Objects.equals(this.directorTenure, legalContract.directorTenure) &&
        Objects.equals(this.issueDate, legalContract.issueDate) &&
        Objects.equals(this.contractType, legalContract.contractType) &&
        Objects.equals(this.personAuthorities, legalContract.personAuthorities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyIssueAuthorityID, issueAuthorityContractNumber, companyDuration, numberOfShares, shareValue, capital, directorTenure, issueDate, contractType, personAuthorities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegalContract {\n");
    
    sb.append("    companyIssueAuthorityID: ").append(toIndentedString(companyIssueAuthorityID)).append("\n");
    sb.append("    issueAuthorityContractNumber: ").append(toIndentedString(issueAuthorityContractNumber)).append("\n");
    sb.append("    companyDuration: ").append(toIndentedString(companyDuration)).append("\n");
    sb.append("    numberOfShares: ").append(toIndentedString(numberOfShares)).append("\n");
    sb.append("    shareValue: ").append(toIndentedString(shareValue)).append("\n");
    sb.append("    capital: ").append(toIndentedString(capital)).append("\n");
    sb.append("    directorTenure: ").append(toIndentedString(directorTenure)).append("\n");
    sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
    sb.append("    contractType: ").append(toIndentedString(contractType)).append("\n");
    sb.append("    personAuthorities: ").append(toIndentedString(personAuthorities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
