/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Objects;
/**
 * LicenceType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class LicenceType {
  @JsonProperty("DUL")
  private String DUL = null;

  @JsonProperty("issueAuthorityLicenceNumber")
  private String issueAuthorityLicenceNumber = null;

  @JsonProperty("issueDate")
  private LocalDate issueDate = null;

  @JsonProperty("expiryDate")
  private LocalDate expiryDate = null;

  @JsonProperty("cancellationDate")
  private LocalDate cancellationDate = null;

  @JsonProperty("freezeStartDate")
  private LocalDate freezeStartDate = null;

  @JsonProperty("freezeEndDate")
  private LocalDate freezeEndDate = null;

  @JsonProperty("category")
  private Integer category = null;

  @JsonProperty("activityType")
  private Integer activityType = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("companyIssueAuthorityID")
  private String companyIssueAuthorityID = null;

  @JsonProperty("isMainLicence")
  private Boolean isMainLicence = null;

  @JsonProperty("dubaiCoCNumber")
  private String dubaiCoCNumber = null;

  @JsonProperty("liquidationDate")
  private LocalDate liquidationDate = null;

  @JsonProperty("ICPEstablishmentCard")
  private String icPEstablishmentCard = null;

  @JsonProperty("MOHREEstablishmentCard")
  private String moHREEstablishmentCard = null;

  @JsonProperty("DUNSNumber")
  private String duNSNumber = null;

  @JsonProperty("TIN")
  private String TIN = null;

  @JsonProperty("initialApproval")
  private String initialApproval = null;

  @JsonProperty("initialApprovalIssueDate")
  private LocalDate initialApprovalIssueDate = null;

  @JsonProperty("initialApprovalExpiryDate")
  private LocalDate initialApprovalExpiryDate = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("mobile")
  private String mobile = null;

  @JsonProperty("phone")
  private String phone = null;

  @JsonProperty("logo")
  private String logo = null;

  @JsonProperty("lastUpdatedBy")
  private Integer lastUpdatedBy = null;

  @JsonProperty("isMobileVerified")
  private Boolean isMobileVerified = null;

  @JsonProperty("mobileVerificationDate")
  private OffsetDateTime mobileVerificationDate = null;

  @JsonProperty("mobileVerificationChannel")
  private Integer mobileVerificationChannel = null;

  @JsonProperty("isEmailVerified")
  private Boolean isEmailVerified = null;

  @JsonProperty("emailVerificationDate")
  private OffsetDateTime emailVerificationDate = null;

  @JsonProperty("emailVerificationChannel")
  private Integer emailVerificationChannel = null;

  @JsonProperty("isScreened")
  private Boolean isScreened = null;

  @JsonProperty("screeningDate")
  private OffsetDateTime screeningDate = null;

  @JsonProperty("screeningChannel")
  private Integer screeningChannel = null;

  @JsonProperty("isExemptDULCriteriaCheck")
  private Boolean isExemptDULCriteriaCheck = null;

  public LicenceType DUL(String DUL) {
    this.DUL = DUL;
    return this;
  }

   /**
   * Get DUL
   * @return DUL
  **/

  public String getDUL() {
    return DUL;
  }

  public void setDUL(String DUL) {
    this.DUL = DUL;
  }

  public LicenceType issueAuthorityLicenceNumber(String issueAuthorityLicenceNumber) {
    this.issueAuthorityLicenceNumber = issueAuthorityLicenceNumber;
    return this;
  }

   /**
   * Get issueAuthorityLicenceNumber
   * @return issueAuthorityLicenceNumber
  **/

  public String getIssueAuthorityLicenceNumber() {
    return issueAuthorityLicenceNumber;
  }

  public void setIssueAuthorityLicenceNumber(String issueAuthorityLicenceNumber) {
    this.issueAuthorityLicenceNumber = issueAuthorityLicenceNumber;
  }

  public LicenceType issueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
    return this;
  }

   /**
   * Get issueDate
   * @return issueDate
  **/

  public LocalDate getIssueDate() {
    return issueDate;
  }

  public void setIssueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
  }

  public LicenceType expiryDate(LocalDate expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/

  public LocalDate getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(LocalDate expiryDate) {
    this.expiryDate = expiryDate;
  }

  public LicenceType cancellationDate(LocalDate cancellationDate) {
    this.cancellationDate = cancellationDate;
    return this;
  }

   /**
   * Get cancellationDate
   * @return cancellationDate
  **/

  public LocalDate getCancellationDate() {
    return cancellationDate;
  }

  public void setCancellationDate(LocalDate cancellationDate) {
    this.cancellationDate = cancellationDate;
  }

  public LicenceType freezeStartDate(LocalDate freezeStartDate) {
    this.freezeStartDate = freezeStartDate;
    return this;
  }

   /**
   * Get freezeStartDate
   * @return freezeStartDate
  **/

  public LocalDate getFreezeStartDate() {
    return freezeStartDate;
  }

  public void setFreezeStartDate(LocalDate freezeStartDate) {
    this.freezeStartDate = freezeStartDate;
  }

  public LicenceType freezeEndDate(LocalDate freezeEndDate) {
    this.freezeEndDate = freezeEndDate;
    return this;
  }

   /**
   * Get freezeEndDate
   * @return freezeEndDate
  **/

  public LocalDate getFreezeEndDate() {
    return freezeEndDate;
  }

  public void setFreezeEndDate(LocalDate freezeEndDate) {
    this.freezeEndDate = freezeEndDate;
  }

  public LicenceType category(Integer category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/

  public Integer getCategory() {
    return category;
  }

  public void setCategory(Integer category) {
    this.category = category;
  }

  public LicenceType activityType(Integer activityType) {
    this.activityType = activityType;
    return this;
  }

   /**
   * Get activityType
   * @return activityType
  **/

  public Integer getActivityType() {
    return activityType;
  }

  public void setActivityType(Integer activityType) {
    this.activityType = activityType;
  }

  public LicenceType status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/

  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public LicenceType companyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
    return this;
  }

   /**
   * Get companyIssueAuthorityID
   * @return companyIssueAuthorityID
  **/

  public String getCompanyIssueAuthorityID() {
    return companyIssueAuthorityID;
  }

  public void setCompanyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
  }

  public LicenceType isMainLicence(Boolean isMainLicence) {
    this.isMainLicence = isMainLicence;
    return this;
  }

   /**
   * Get isMainLicence
   * @return isMainLicence
  **/

  public Boolean isIsMainLicence() {
    return isMainLicence;
  }

  public void setIsMainLicence(Boolean isMainLicence) {
    this.isMainLicence = isMainLicence;
  }

  public LicenceType dubaiCoCNumber(String dubaiCoCNumber) {
    this.dubaiCoCNumber = dubaiCoCNumber;
    return this;
  }

   /**
   * Get dubaiCoCNumber
   * @return dubaiCoCNumber
  **/

  public String getDubaiCoCNumber() {
    return dubaiCoCNumber;
  }

  public void setDubaiCoCNumber(String dubaiCoCNumber) {
    this.dubaiCoCNumber = dubaiCoCNumber;
  }

  public LicenceType liquidationDate(LocalDate liquidationDate) {
    this.liquidationDate = liquidationDate;
    return this;
  }

   /**
   * Get liquidationDate
   * @return liquidationDate
  **/

  public LocalDate getLiquidationDate() {
    return liquidationDate;
  }

  public void setLiquidationDate(LocalDate liquidationDate) {
    this.liquidationDate = liquidationDate;
  }

  public LicenceType icPEstablishmentCard(String icPEstablishmentCard) {
    this.icPEstablishmentCard = icPEstablishmentCard;
    return this;
  }

   /**
   * Get icPEstablishmentCard
   * @return icPEstablishmentCard
  **/

  public String getIcPEstablishmentCard() {
    return icPEstablishmentCard;
  }

  public void setIcPEstablishmentCard(String icPEstablishmentCard) {
    this.icPEstablishmentCard = icPEstablishmentCard;
  }

  public LicenceType moHREEstablishmentCard(String moHREEstablishmentCard) {
    this.moHREEstablishmentCard = moHREEstablishmentCard;
    return this;
  }

   /**
   * Get moHREEstablishmentCard
   * @return moHREEstablishmentCard
  **/

  public String getMoHREEstablishmentCard() {
    return moHREEstablishmentCard;
  }

  public void setMoHREEstablishmentCard(String moHREEstablishmentCard) {
    this.moHREEstablishmentCard = moHREEstablishmentCard;
  }

  public LicenceType duNSNumber(String duNSNumber) {
    this.duNSNumber = duNSNumber;
    return this;
  }

   /**
   * Get duNSNumber
   * @return duNSNumber
  **/

  public String getDuNSNumber() {
    return duNSNumber;
  }

  public void setDuNSNumber(String duNSNumber) {
    this.duNSNumber = duNSNumber;
  }

  public LicenceType TIN(String TIN) {
    this.TIN = TIN;
    return this;
  }

   /**
   * Get TIN
   * @return TIN
  **/

  public String getTIN() {
    return TIN;
  }

  public void setTIN(String TIN) {
    this.TIN = TIN;
  }

  public LicenceType initialApproval(String initialApproval) {
    this.initialApproval = initialApproval;
    return this;
  }

   /**
   * Get initialApproval
   * @return initialApproval
  **/

  public String getInitialApproval() {
    return initialApproval;
  }

  public void setInitialApproval(String initialApproval) {
    this.initialApproval = initialApproval;
  }

  public LicenceType initialApprovalIssueDate(LocalDate initialApprovalIssueDate) {
    this.initialApprovalIssueDate = initialApprovalIssueDate;
    return this;
  }

   /**
   * Get initialApprovalIssueDate
   * @return initialApprovalIssueDate
  **/

  public LocalDate getInitialApprovalIssueDate() {
    return initialApprovalIssueDate;
  }

  public void setInitialApprovalIssueDate(LocalDate initialApprovalIssueDate) {
    this.initialApprovalIssueDate = initialApprovalIssueDate;
  }

  public LicenceType initialApprovalExpiryDate(LocalDate initialApprovalExpiryDate) {
    this.initialApprovalExpiryDate = initialApprovalExpiryDate;
    return this;
  }

   /**
   * Get initialApprovalExpiryDate
   * @return initialApprovalExpiryDate
  **/

  public LocalDate getInitialApprovalExpiryDate() {
    return initialApprovalExpiryDate;
  }

  public void setInitialApprovalExpiryDate(LocalDate initialApprovalExpiryDate) {
    this.initialApprovalExpiryDate = initialApprovalExpiryDate;
  }

  public LicenceType email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public LicenceType mobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Get mobile
   * @return mobile
  **/

  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public LicenceType phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/

  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public LicenceType logo(String logo) {
    this.logo = logo;
    return this;
  }

   /**
   * Get logo
   * @return logo
  **/

  public String getLogo() {
    return logo;
  }

  public void setLogo(String logo) {
    this.logo = logo;
  }

  public LicenceType lastUpdatedBy(Integer lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * Get lastUpdatedBy
   * @return lastUpdatedBy
  **/

  public Integer getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(Integer lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public LicenceType isMobileVerified(Boolean isMobileVerified) {
    this.isMobileVerified = isMobileVerified;
    return this;
  }

   /**
   * Get isMobileVerified
   * @return isMobileVerified
  **/

  public Boolean isIsMobileVerified() {
    return isMobileVerified;
  }

  public void setIsMobileVerified(Boolean isMobileVerified) {
    this.isMobileVerified = isMobileVerified;
  }

  public LicenceType mobileVerificationDate(OffsetDateTime mobileVerificationDate) {
    this.mobileVerificationDate = mobileVerificationDate;
    return this;
  }

   /**
   * Get mobileVerificationDate
   * @return mobileVerificationDate
  **/

  public OffsetDateTime getMobileVerificationDate() {
    return mobileVerificationDate;
  }

  public void setMobileVerificationDate(OffsetDateTime mobileVerificationDate) {
    this.mobileVerificationDate = mobileVerificationDate;
  }

  public LicenceType mobileVerificationChannel(Integer mobileVerificationChannel) {
    this.mobileVerificationChannel = mobileVerificationChannel;
    return this;
  }

   /**
   * Get mobileVerificationChannel
   * @return mobileVerificationChannel
  **/

  public Integer getMobileVerificationChannel() {
    return mobileVerificationChannel;
  }

  public void setMobileVerificationChannel(Integer mobileVerificationChannel) {
    this.mobileVerificationChannel = mobileVerificationChannel;
  }

  public LicenceType isEmailVerified(Boolean isEmailVerified) {
    this.isEmailVerified = isEmailVerified;
    return this;
  }

   /**
   * Get isEmailVerified
   * @return isEmailVerified
  **/

  public Boolean isIsEmailVerified() {
    return isEmailVerified;
  }

  public void setIsEmailVerified(Boolean isEmailVerified) {
    this.isEmailVerified = isEmailVerified;
  }

  public LicenceType emailVerificationDate(OffsetDateTime emailVerificationDate) {
    this.emailVerificationDate = emailVerificationDate;
    return this;
  }

   /**
   * Get emailVerificationDate
   * @return emailVerificationDate
  **/

  public OffsetDateTime getEmailVerificationDate() {
    return emailVerificationDate;
  }

  public void setEmailVerificationDate(OffsetDateTime emailVerificationDate) {
    this.emailVerificationDate = emailVerificationDate;
  }

  public LicenceType emailVerificationChannel(Integer emailVerificationChannel) {
    this.emailVerificationChannel = emailVerificationChannel;
    return this;
  }

   /**
   * Get emailVerificationChannel
   * @return emailVerificationChannel
  **/

  public Integer getEmailVerificationChannel() {
    return emailVerificationChannel;
  }

  public void setEmailVerificationChannel(Integer emailVerificationChannel) {
    this.emailVerificationChannel = emailVerificationChannel;
  }

  public LicenceType isScreened(Boolean isScreened) {
    this.isScreened = isScreened;
    return this;
  }

   /**
   * Get isScreened
   * @return isScreened
  **/

  public Boolean isIsScreened() {
    return isScreened;
  }

  public void setIsScreened(Boolean isScreened) {
    this.isScreened = isScreened;
  }

  public LicenceType screeningDate(OffsetDateTime screeningDate) {
    this.screeningDate = screeningDate;
    return this;
  }

   /**
   * Get screeningDate
   * @return screeningDate
  **/

  public OffsetDateTime getScreeningDate() {
    return screeningDate;
  }

  public void setScreeningDate(OffsetDateTime screeningDate) {
    this.screeningDate = screeningDate;
  }

  public LicenceType screeningChannel(Integer screeningChannel) {
    this.screeningChannel = screeningChannel;
    return this;
  }

   /**
   * Get screeningChannel
   * @return screeningChannel
  **/

  public Integer getScreeningChannel() {
    return screeningChannel;
  }

  public void setScreeningChannel(Integer screeningChannel) {
    this.screeningChannel = screeningChannel;
  }

  public LicenceType isExemptDULCriteriaCheck(Boolean isExemptDULCriteriaCheck) {
    this.isExemptDULCriteriaCheck = isExemptDULCriteriaCheck;
    return this;
  }

   /**
   * Get isExemptDULCriteriaCheck
   * @return isExemptDULCriteriaCheck
  **/

  public Boolean isIsExemptDULCriteriaCheck() {
    return isExemptDULCriteriaCheck;
  }

  public void setIsExemptDULCriteriaCheck(Boolean isExemptDULCriteriaCheck) {
    this.isExemptDULCriteriaCheck = isExemptDULCriteriaCheck;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenceType licenceType = (LicenceType) o;
    return Objects.equals(this.DUL, licenceType.DUL) &&
        Objects.equals(this.issueAuthorityLicenceNumber, licenceType.issueAuthorityLicenceNumber) &&
        Objects.equals(this.issueDate, licenceType.issueDate) &&
        Objects.equals(this.expiryDate, licenceType.expiryDate) &&
        Objects.equals(this.cancellationDate, licenceType.cancellationDate) &&
        Objects.equals(this.freezeStartDate, licenceType.freezeStartDate) &&
        Objects.equals(this.freezeEndDate, licenceType.freezeEndDate) &&
        Objects.equals(this.category, licenceType.category) &&
        Objects.equals(this.activityType, licenceType.activityType) &&
        Objects.equals(this.status, licenceType.status) &&
        Objects.equals(this.companyIssueAuthorityID, licenceType.companyIssueAuthorityID) &&
        Objects.equals(this.isMainLicence, licenceType.isMainLicence) &&
        Objects.equals(this.dubaiCoCNumber, licenceType.dubaiCoCNumber) &&
        Objects.equals(this.liquidationDate, licenceType.liquidationDate) &&
        Objects.equals(this.icPEstablishmentCard, licenceType.icPEstablishmentCard) &&
        Objects.equals(this.moHREEstablishmentCard, licenceType.moHREEstablishmentCard) &&
        Objects.equals(this.duNSNumber, licenceType.duNSNumber) &&
        Objects.equals(this.TIN, licenceType.TIN) &&
        Objects.equals(this.initialApproval, licenceType.initialApproval) &&
        Objects.equals(this.initialApprovalIssueDate, licenceType.initialApprovalIssueDate) &&
        Objects.equals(this.initialApprovalExpiryDate, licenceType.initialApprovalExpiryDate) &&
        Objects.equals(this.email, licenceType.email) &&
        Objects.equals(this.mobile, licenceType.mobile) &&
        Objects.equals(this.phone, licenceType.phone) &&
        Objects.equals(this.logo, licenceType.logo) &&
        Objects.equals(this.lastUpdatedBy, licenceType.lastUpdatedBy) &&
        Objects.equals(this.isMobileVerified, licenceType.isMobileVerified) &&
        Objects.equals(this.mobileVerificationDate, licenceType.mobileVerificationDate) &&
        Objects.equals(this.mobileVerificationChannel, licenceType.mobileVerificationChannel) &&
        Objects.equals(this.isEmailVerified, licenceType.isEmailVerified) &&
        Objects.equals(this.emailVerificationDate, licenceType.emailVerificationDate) &&
        Objects.equals(this.emailVerificationChannel, licenceType.emailVerificationChannel) &&
        Objects.equals(this.isScreened, licenceType.isScreened) &&
        Objects.equals(this.screeningDate, licenceType.screeningDate) &&
        Objects.equals(this.screeningChannel, licenceType.screeningChannel) &&
        Objects.equals(this.isExemptDULCriteriaCheck, licenceType.isExemptDULCriteriaCheck);
  }

  @Override
  public int hashCode() {
    return Objects.hash(DUL, issueAuthorityLicenceNumber, issueDate, expiryDate, cancellationDate, freezeStartDate, freezeEndDate, category, activityType, status, companyIssueAuthorityID, isMainLicence, dubaiCoCNumber, liquidationDate, icPEstablishmentCard, moHREEstablishmentCard, duNSNumber, TIN, initialApproval, initialApprovalIssueDate, initialApprovalExpiryDate, email, mobile, phone, logo, lastUpdatedBy, isMobileVerified, mobileVerificationDate, mobileVerificationChannel, isEmailVerified, emailVerificationDate, emailVerificationChannel, isScreened, screeningDate, screeningChannel, isExemptDULCriteriaCheck);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenceType {\n");
    
    sb.append("    DUL: ").append(toIndentedString(DUL)).append("\n");
    sb.append("    issueAuthorityLicenceNumber: ").append(toIndentedString(issueAuthorityLicenceNumber)).append("\n");
    sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    cancellationDate: ").append(toIndentedString(cancellationDate)).append("\n");
    sb.append("    freezeStartDate: ").append(toIndentedString(freezeStartDate)).append("\n");
    sb.append("    freezeEndDate: ").append(toIndentedString(freezeEndDate)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    activityType: ").append(toIndentedString(activityType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    companyIssueAuthorityID: ").append(toIndentedString(companyIssueAuthorityID)).append("\n");
    sb.append("    isMainLicence: ").append(toIndentedString(isMainLicence)).append("\n");
    sb.append("    dubaiCoCNumber: ").append(toIndentedString(dubaiCoCNumber)).append("\n");
    sb.append("    liquidationDate: ").append(toIndentedString(liquidationDate)).append("\n");
    sb.append("    icPEstablishmentCard: ").append(toIndentedString(icPEstablishmentCard)).append("\n");
    sb.append("    moHREEstablishmentCard: ").append(toIndentedString(moHREEstablishmentCard)).append("\n");
    sb.append("    duNSNumber: ").append(toIndentedString(duNSNumber)).append("\n");
    sb.append("    TIN: ").append(toIndentedString(TIN)).append("\n");
    sb.append("    initialApproval: ").append(toIndentedString(initialApproval)).append("\n");
    sb.append("    initialApprovalIssueDate: ").append(toIndentedString(initialApprovalIssueDate)).append("\n");
    sb.append("    initialApprovalExpiryDate: ").append(toIndentedString(initialApprovalExpiryDate)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    isMobileVerified: ").append(toIndentedString(isMobileVerified)).append("\n");
    sb.append("    mobileVerificationDate: ").append(toIndentedString(mobileVerificationDate)).append("\n");
    sb.append("    mobileVerificationChannel: ").append(toIndentedString(mobileVerificationChannel)).append("\n");
    sb.append("    isEmailVerified: ").append(toIndentedString(isEmailVerified)).append("\n");
    sb.append("    emailVerificationDate: ").append(toIndentedString(emailVerificationDate)).append("\n");
    sb.append("    emailVerificationChannel: ").append(toIndentedString(emailVerificationChannel)).append("\n");
    sb.append("    isScreened: ").append(toIndentedString(isScreened)).append("\n");
    sb.append("    screeningDate: ").append(toIndentedString(screeningDate)).append("\n");
    sb.append("    screeningChannel: ").append(toIndentedString(screeningChannel)).append("\n");
    sb.append("    isExemptDULCriteriaCheck: ").append(toIndentedString(isExemptDULCriteriaCheck)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
