/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.OffsetDateTime;
import java.util.Objects;
/**
 * LicenceMembers
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class LicenceMembers {
  @JsonProperty("legalEntity")
  private LegalEntityType legalEntity = null;

  @JsonProperty("issueAuthorityLicenceNumber")
  private String issueAuthorityLicenceNumber = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("addDate")
  private OffsetDateTime addDate = null;

  @JsonProperty("cancelDate")
  private OffsetDateTime cancelDate = null;

  @JsonProperty("memberRole")
  private Integer memberRole = null;

  public LicenceMembers legalEntity(LegalEntityType legalEntity) {
    this.legalEntity = legalEntity;
    return this;
  }

   /**
   * Get legalEntity
   * @return legalEntity
  **/

  public LegalEntityType getLegalEntity() {
    return legalEntity;
  }

  public void setLegalEntity(LegalEntityType legalEntity) {
    this.legalEntity = legalEntity;
  }

  public LicenceMembers issueAuthorityLicenceNumber(String issueAuthorityLicenceNumber) {
    this.issueAuthorityLicenceNumber = issueAuthorityLicenceNumber;
    return this;
  }

   /**
   * Get issueAuthorityLicenceNumber
   * @return issueAuthorityLicenceNumber
  **/

  public String getIssueAuthorityLicenceNumber() {
    return issueAuthorityLicenceNumber;
  }

  public void setIssueAuthorityLicenceNumber(String issueAuthorityLicenceNumber) {
    this.issueAuthorityLicenceNumber = issueAuthorityLicenceNumber;
  }

  public LicenceMembers status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/

  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public LicenceMembers addDate(OffsetDateTime addDate) {
    this.addDate = addDate;
    return this;
  }

   /**
   * Get addDate
   * @return addDate
  **/

  public OffsetDateTime getAddDate() {
    return addDate;
  }

  public void setAddDate(OffsetDateTime addDate) {
    this.addDate = addDate;
  }

  public LicenceMembers cancelDate(OffsetDateTime cancelDate) {
    this.cancelDate = cancelDate;
    return this;
  }

   /**
   * Get cancelDate
   * @return cancelDate
  **/

  public OffsetDateTime getCancelDate() {
    return cancelDate;
  }

  public void setCancelDate(OffsetDateTime cancelDate) {
    this.cancelDate = cancelDate;
  }

  public LicenceMembers memberRole(Integer memberRole) {
    this.memberRole = memberRole;
    return this;
  }

   /**
   * Get memberRole
   * @return memberRole
  **/

  public Integer getMemberRole() {
    return memberRole;
  }

  public void setMemberRole(Integer memberRole) {
    this.memberRole = memberRole;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenceMembers licenceMembers = (LicenceMembers) o;
    return Objects.equals(this.legalEntity, licenceMembers.legalEntity) &&
        Objects.equals(this.issueAuthorityLicenceNumber, licenceMembers.issueAuthorityLicenceNumber) &&
        Objects.equals(this.status, licenceMembers.status) &&
        Objects.equals(this.addDate, licenceMembers.addDate) &&
        Objects.equals(this.cancelDate, licenceMembers.cancelDate) &&
        Objects.equals(this.memberRole, licenceMembers.memberRole);
  }

  @Override
  public int hashCode() {
    return Objects.hash(legalEntity, issueAuthorityLicenceNumber, status, addDate, cancelDate, memberRole);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenceMembers {\n");
    
    sb.append("    legalEntity: ").append(toIndentedString(legalEntity)).append("\n");
    sb.append("    issueAuthorityLicenceNumber: ").append(toIndentedString(issueAuthorityLicenceNumber)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    addDate: ").append(toIndentedString(addDate)).append("\n");
    sb.append("    cancelDate: ").append(toIndentedString(cancelDate)).append("\n");
    sb.append("    memberRole: ").append(toIndentedString(memberRole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
