/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import java.util.Objects;
/**
 * LicenceAddressType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class LicenceAddressType {
  @JsonProperty("issueAuthorityLicenceNumber")
  private String issueAuthorityLicenceNumber = null;

  @JsonProperty("areaCode")
  private String areaCode = null;

  @JsonProperty("addressType")
  private Integer addressType = null;

  @JsonProperty("poBox")
  private String poBox = null;

  @JsonProperty("addressLine1")
  private String addressLine1 = null;

  @JsonProperty("addressLine2")
  private String addressLine2 = null;

  @JsonProperty("floor")
  private String floor = null;

  @JsonProperty("street")
  private String street = null;

  @JsonProperty("unitType")
  private Integer unitType = null;

  @JsonProperty("unitNumber")
  private String unitNumber = null;

  @JsonProperty("parcelID")
  private String parcelID = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("emirate")
  private Integer emirate = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("freezone")
  private Integer freezone = null;

  @JsonProperty("longitude")
  private BigDecimal longitude = null;

  @JsonProperty("latitude")
  private BigDecimal latitude = null;

  public LicenceAddressType issueAuthorityLicenceNumber(String issueAuthorityLicenceNumber) {
    this.issueAuthorityLicenceNumber = issueAuthorityLicenceNumber;
    return this;
  }

   /**
   * Get issueAuthorityLicenceNumber
   * @return issueAuthorityLicenceNumber
  **/

  public String getIssueAuthorityLicenceNumber() {
    return issueAuthorityLicenceNumber;
  }

  public void setIssueAuthorityLicenceNumber(String issueAuthorityLicenceNumber) {
    this.issueAuthorityLicenceNumber = issueAuthorityLicenceNumber;
  }

  public LicenceAddressType areaCode(String areaCode) {
    this.areaCode = areaCode;
    return this;
  }

   /**
   * Get areaCode
   * @return areaCode
  **/

  public String getAreaCode() {
    return areaCode;
  }

  public void setAreaCode(String areaCode) {
    this.areaCode = areaCode;
  }

  public LicenceAddressType addressType(Integer addressType) {
    this.addressType = addressType;
    return this;
  }

   /**
   * Get addressType
   * @return addressType
  **/

  public Integer getAddressType() {
    return addressType;
  }

  public void setAddressType(Integer addressType) {
    this.addressType = addressType;
  }

  public LicenceAddressType poBox(String poBox) {
    this.poBox = poBox;
    return this;
  }

   /**
   * Get poBox
   * @return poBox
  **/

  public String getPoBox() {
    return poBox;
  }

  public void setPoBox(String poBox) {
    this.poBox = poBox;
  }

  public LicenceAddressType addressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * Get addressLine1
   * @return addressLine1
  **/

  public String getAddressLine1() {
    return addressLine1;
  }

  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }

  public LicenceAddressType addressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
    return this;
  }

   /**
   * Get addressLine2
   * @return addressLine2
  **/

  public String getAddressLine2() {
    return addressLine2;
  }

  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }

  public LicenceAddressType floor(String floor) {
    this.floor = floor;
    return this;
  }

   /**
   * Get floor
   * @return floor
  **/

  public String getFloor() {
    return floor;
  }

  public void setFloor(String floor) {
    this.floor = floor;
  }

  public LicenceAddressType street(String street) {
    this.street = street;
    return this;
  }

   /**
   * Get street
   * @return street
  **/

  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public LicenceAddressType unitType(Integer unitType) {
    this.unitType = unitType;
    return this;
  }

   /**
   * Get unitType
   * @return unitType
  **/

  public Integer getUnitType() {
    return unitType;
  }

  public void setUnitType(Integer unitType) {
    this.unitType = unitType;
  }

  public LicenceAddressType unitNumber(String unitNumber) {
    this.unitNumber = unitNumber;
    return this;
  }

   /**
   * Get unitNumber
   * @return unitNumber
  **/

  public String getUnitNumber() {
    return unitNumber;
  }

  public void setUnitNumber(String unitNumber) {
    this.unitNumber = unitNumber;
  }

  public LicenceAddressType parcelID(String parcelID) {
    this.parcelID = parcelID;
    return this;
  }

   /**
   * Get parcelID
   * @return parcelID
  **/

  public String getParcelID() {
    return parcelID;
  }

  public void setParcelID(String parcelID) {
    this.parcelID = parcelID;
  }

  public LicenceAddressType country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/

  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public LicenceAddressType emirate(Integer emirate) {
    this.emirate = emirate;
    return this;
  }

   /**
   * Get emirate
   * @return emirate
  **/

  public Integer getEmirate() {
    return emirate;
  }

  public void setEmirate(Integer emirate) {
    this.emirate = emirate;
  }

  public LicenceAddressType state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/

  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public LicenceAddressType freezone(Integer freezone) {
    this.freezone = freezone;
    return this;
  }

   /**
   * Get freezone
   * @return freezone
  **/

  public Integer getFreezone() {
    return freezone;
  }

  public void setFreezone(Integer freezone) {
    this.freezone = freezone;
  }

  public LicenceAddressType longitude(BigDecimal longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/

  public BigDecimal getLongitude() {
    return longitude;
  }

  public void setLongitude(BigDecimal longitude) {
    this.longitude = longitude;
  }

  public LicenceAddressType latitude(BigDecimal latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/

  public BigDecimal getLatitude() {
    return latitude;
  }

  public void setLatitude(BigDecimal latitude) {
    this.latitude = latitude;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenceAddressType licenceAddressType = (LicenceAddressType) o;
    return Objects.equals(this.issueAuthorityLicenceNumber, licenceAddressType.issueAuthorityLicenceNumber) &&
        Objects.equals(this.areaCode, licenceAddressType.areaCode) &&
        Objects.equals(this.addressType, licenceAddressType.addressType) &&
        Objects.equals(this.poBox, licenceAddressType.poBox) &&
        Objects.equals(this.addressLine1, licenceAddressType.addressLine1) &&
        Objects.equals(this.addressLine2, licenceAddressType.addressLine2) &&
        Objects.equals(this.floor, licenceAddressType.floor) &&
        Objects.equals(this.street, licenceAddressType.street) &&
        Objects.equals(this.unitType, licenceAddressType.unitType) &&
        Objects.equals(this.unitNumber, licenceAddressType.unitNumber) &&
        Objects.equals(this.parcelID, licenceAddressType.parcelID) &&
        Objects.equals(this.country, licenceAddressType.country) &&
        Objects.equals(this.emirate, licenceAddressType.emirate) &&
        Objects.equals(this.state, licenceAddressType.state) &&
        Objects.equals(this.freezone, licenceAddressType.freezone) &&
        Objects.equals(this.longitude, licenceAddressType.longitude) &&
        Objects.equals(this.latitude, licenceAddressType.latitude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issueAuthorityLicenceNumber, areaCode, addressType, poBox, addressLine1, addressLine2, floor, street, unitType, unitNumber, parcelID, country, emirate, state, freezone, longitude, latitude);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenceAddressType {\n");
    
    sb.append("    issueAuthorityLicenceNumber: ").append(toIndentedString(issueAuthorityLicenceNumber)).append("\n");
    sb.append("    areaCode: ").append(toIndentedString(areaCode)).append("\n");
    sb.append("    addressType: ").append(toIndentedString(addressType)).append("\n");
    sb.append("    poBox: ").append(toIndentedString(poBox)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    floor: ").append(toIndentedString(floor)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    unitType: ").append(toIndentedString(unitType)).append("\n");
    sb.append("    unitNumber: ").append(toIndentedString(unitNumber)).append("\n");
    sb.append("    parcelID: ").append(toIndentedString(parcelID)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    emirate: ").append(toIndentedString(emirate)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    freezone: ").append(toIndentedString(freezone)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
