/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Objects;
/**
 * Ownerships
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class Ownerships {
  @JsonProperty("companyIssueAuthorityID")
  private String companyIssueAuthorityID = null;

  @JsonProperty("legalEntity")
  private LegalEntityType legalEntity = null;

  @JsonProperty("ownershipShare")
  private BigDecimal ownershipShare = null;

  @JsonProperty("profitLossShare")
  private BigDecimal profitLossShare = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("addDate")
  private OffsetDateTime addDate = null;

  @JsonProperty("cancelDate")
  private OffsetDateTime cancelDate = null;

  @JsonProperty("investorRole")
  private Integer investorRole = null;

  @JsonProperty("displaySequence")
  private Integer displaySequence = null;

  public Ownerships companyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
    return this;
  }

   /**
   * Get companyIssueAuthorityID
   * @return companyIssueAuthorityID
  **/

  public String getCompanyIssueAuthorityID() {
    return companyIssueAuthorityID;
  }

  public void setCompanyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
  }

  public Ownerships legalEntity(LegalEntityType legalEntity) {
    this.legalEntity = legalEntity;
    return this;
  }

   /**
   * Get legalEntity
   * @return legalEntity
  **/

  public LegalEntityType getLegalEntity() {
    return legalEntity;
  }

  public void setLegalEntity(LegalEntityType legalEntity) {
    this.legalEntity = legalEntity;
  }

  public Ownerships ownershipShare(BigDecimal ownershipShare) {
    this.ownershipShare = ownershipShare;
    return this;
  }

   /**
   * Get ownershipShare
   * @return ownershipShare
  **/

  public BigDecimal getOwnershipShare() {
    return ownershipShare;
  }

  public void setOwnershipShare(BigDecimal ownershipShare) {
    this.ownershipShare = ownershipShare;
  }

  public Ownerships profitLossShare(BigDecimal profitLossShare) {
    this.profitLossShare = profitLossShare;
    return this;
  }

   /**
   * Get profitLossShare
   * @return profitLossShare
  **/

  public BigDecimal getProfitLossShare() {
    return profitLossShare;
  }

  public void setProfitLossShare(BigDecimal profitLossShare) {
    this.profitLossShare = profitLossShare;
  }

  public Ownerships status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/

  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Ownerships addDate(OffsetDateTime addDate) {
    this.addDate = addDate;
    return this;
  }

   /**
   * Get addDate
   * @return addDate
  **/

  public OffsetDateTime getAddDate() {
    return addDate;
  }

  public void setAddDate(OffsetDateTime addDate) {
    this.addDate = addDate;
  }

  public Ownerships cancelDate(OffsetDateTime cancelDate) {
    this.cancelDate = cancelDate;
    return this;
  }

   /**
   * Get cancelDate
   * @return cancelDate
  **/

  public OffsetDateTime getCancelDate() {
    return cancelDate;
  }

  public void setCancelDate(OffsetDateTime cancelDate) {
    this.cancelDate = cancelDate;
  }

  public Ownerships investorRole(Integer investorRole) {
    this.investorRole = investorRole;
    return this;
  }

   /**
   * Get investorRole
   * @return investorRole
  **/

  public Integer getInvestorRole() {
    return investorRole;
  }

  public void setInvestorRole(Integer investorRole) {
    this.investorRole = investorRole;
  }

  public Ownerships displaySequence(Integer displaySequence) {
    this.displaySequence = displaySequence;
    return this;
  }

   /**
   * Get displaySequence
   * @return displaySequence
  **/

  public Integer getDisplaySequence() {
    return displaySequence;
  }

  public void setDisplaySequence(Integer displaySequence) {
    this.displaySequence = displaySequence;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ownerships ownerships = (Ownerships) o;
    return Objects.equals(this.companyIssueAuthorityID, ownerships.companyIssueAuthorityID) &&
        Objects.equals(this.legalEntity, ownerships.legalEntity) &&
        Objects.equals(this.ownershipShare, ownerships.ownershipShare) &&
        Objects.equals(this.profitLossShare, ownerships.profitLossShare) &&
        Objects.equals(this.status, ownerships.status) &&
        Objects.equals(this.addDate, ownerships.addDate) &&
        Objects.equals(this.cancelDate, ownerships.cancelDate) &&
        Objects.equals(this.investorRole, ownerships.investorRole) &&
        Objects.equals(this.displaySequence, ownerships.displaySequence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyIssueAuthorityID, legalEntity, ownershipShare, profitLossShare, status, addDate, cancelDate, investorRole, displaySequence);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ownerships {\n");
    
    sb.append("    companyIssueAuthorityID: ").append(toIndentedString(companyIssueAuthorityID)).append("\n");
    sb.append("    legalEntity: ").append(toIndentedString(legalEntity)).append("\n");
    sb.append("    ownershipShare: ").append(toIndentedString(ownershipShare)).append("\n");
    sb.append("    profitLossShare: ").append(toIndentedString(profitLossShare)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    addDate: ").append(toIndentedString(addDate)).append("\n");
    sb.append("    cancelDate: ").append(toIndentedString(cancelDate)).append("\n");
    sb.append("    investorRole: ").append(toIndentedString(investorRole)).append("\n");
    sb.append("    displaySequence: ").append(toIndentedString(displaySequence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
