/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Objects;
/**
 * PersonType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class PersonType {
  @JsonProperty("personIssueAuthorityID")
  private String personIssueAuthorityID = null;

  @JsonProperty("birthDate")
  private LocalDate birthDate = null;

  @JsonProperty("gender")
  private Integer gender = null;

  @JsonProperty("unifiedID")
  private String unifiedID = null;

  @JsonProperty("emiratesID")
  private String emiratesID = null;

  @JsonProperty("emiratesIDIssueDate")
  private LocalDate emiratesIDIssueDate = null;

  @JsonProperty("emiratesIDExpiryDate")
  private LocalDate emiratesIDExpiryDate = null;

  @JsonProperty("passportNumber")
  private String passportNumber = null;

  @JsonProperty("passportIssueDate")
  private LocalDate passportIssueDate = null;

  @JsonProperty("passportExpiryDate")
  private LocalDate passportExpiryDate = null;

  @JsonProperty("passportIssuePlaceEnglish")
  private String passportIssuePlaceEnglish = null;

  @JsonProperty("passportIssuePlaceArabic")
  private String passportIssuePlaceArabic = null;

  @JsonProperty("passportIssueCountry")
  private String passportIssueCountry = null;

  @JsonProperty("birthPlaceEnglish")
  private String birthPlaceEnglish = null;

  @JsonProperty("birthPlaceArabic")
  private String birthPlaceArabic = null;

  @JsonProperty("birthCountry")
  private String birthCountry = null;

  @JsonProperty("decreeNumber")
  private String decreeNumber = null;

  @JsonProperty("arabicName")
  private String arabicName = null;

  @JsonProperty("englishName")
  private String englishName = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("mobile")
  private String mobile = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("statusReason")
  private Integer statusReason = null;

  @JsonProperty("activePerson")
  private String activePerson = null;

  @JsonProperty("nationality")
  private String nationality = null;

  @JsonProperty("languagePreference")
  private Integer languagePreference = null;

  @JsonProperty("fileNumber")
  private String fileNumber = null;

  @JsonProperty("GCCuid")
  private String gcCuid = null;

  @JsonProperty("familyBookNumber")
  private String familyBookNumber = null;

  @JsonProperty("isVerifiedContact")
  private Boolean isVerifiedContact = null;

  @JsonProperty("lastUpdatedBy")
  private Integer lastUpdatedBy = null;

  @JsonProperty("isMobileVerified")
  private Boolean isMobileVerified = null;

  @JsonProperty("mobileVerificationDate")
  private OffsetDateTime mobileVerificationDate = null;

  @JsonProperty("mobileVerificationChannel")
  private Integer mobileVerificationChannel = null;

  @JsonProperty("isEmailVerified")
  private Boolean isEmailVerified = null;

  @JsonProperty("emailVerificationDate")
  private OffsetDateTime emailVerificationDate = null;

  @JsonProperty("emailVerificationChannel")
  private Integer emailVerificationChannel = null;

  @JsonProperty("isScreened")
  private Boolean isScreened = null;

  @JsonProperty("screeningDate")
  private OffsetDateTime screeningDate = null;

  @JsonProperty("screeningChannel")
  private Integer screeningChannel = null;

  public PersonType personIssueAuthorityID(String personIssueAuthorityID) {
    this.personIssueAuthorityID = personIssueAuthorityID;
    return this;
  }

   /**
   * Get personIssueAuthorityID
   * @return personIssueAuthorityID
  **/

  public String getPersonIssueAuthorityID() {
    return personIssueAuthorityID;
  }

  public void setPersonIssueAuthorityID(String personIssueAuthorityID) {
    this.personIssueAuthorityID = personIssueAuthorityID;
  }

  public PersonType birthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
    return this;
  }

   /**
   * Get birthDate
   * @return birthDate
  **/

  public LocalDate getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
  }

  public PersonType gender(Integer gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/

  public Integer getGender() {
    return gender;
  }

  public void setGender(Integer gender) {
    this.gender = gender;
  }

  public PersonType unifiedID(String unifiedID) {
    this.unifiedID = unifiedID;
    return this;
  }

   /**
   * Get unifiedID
   * @return unifiedID
  **/

  public String getUnifiedID() {
    return unifiedID;
  }

  public void setUnifiedID(String unifiedID) {
    this.unifiedID = unifiedID;
  }

  public PersonType emiratesID(String emiratesID) {
    this.emiratesID = emiratesID;
    return this;
  }

   /**
   * Get emiratesID
   * @return emiratesID
  **/

  public String getEmiratesID() {
    return emiratesID;
  }

  public void setEmiratesID(String emiratesID) {
    this.emiratesID = emiratesID;
  }

  public PersonType emiratesIDIssueDate(LocalDate emiratesIDIssueDate) {
    this.emiratesIDIssueDate = emiratesIDIssueDate;
    return this;
  }

   /**
   * Get emiratesIDIssueDate
   * @return emiratesIDIssueDate
  **/

  public LocalDate getEmiratesIDIssueDate() {
    return emiratesIDIssueDate;
  }

  public void setEmiratesIDIssueDate(LocalDate emiratesIDIssueDate) {
    this.emiratesIDIssueDate = emiratesIDIssueDate;
  }

  public PersonType emiratesIDExpiryDate(LocalDate emiratesIDExpiryDate) {
    this.emiratesIDExpiryDate = emiratesIDExpiryDate;
    return this;
  }

   /**
   * Get emiratesIDExpiryDate
   * @return emiratesIDExpiryDate
  **/

  public LocalDate getEmiratesIDExpiryDate() {
    return emiratesIDExpiryDate;
  }

  public void setEmiratesIDExpiryDate(LocalDate emiratesIDExpiryDate) {
    this.emiratesIDExpiryDate = emiratesIDExpiryDate;
  }

  public PersonType passportNumber(String passportNumber) {
    this.passportNumber = passportNumber;
    return this;
  }

   /**
   * Get passportNumber
   * @return passportNumber
  **/

  public String getPassportNumber() {
    return passportNumber;
  }

  public void setPassportNumber(String passportNumber) {
    this.passportNumber = passportNumber;
  }

  public PersonType passportIssueDate(LocalDate passportIssueDate) {
    this.passportIssueDate = passportIssueDate;
    return this;
  }

   /**
   * Get passportIssueDate
   * @return passportIssueDate
  **/

  public LocalDate getPassportIssueDate() {
    return passportIssueDate;
  }

  public void setPassportIssueDate(LocalDate passportIssueDate) {
    this.passportIssueDate = passportIssueDate;
  }

  public PersonType passportExpiryDate(LocalDate passportExpiryDate) {
    this.passportExpiryDate = passportExpiryDate;
    return this;
  }

   /**
   * Get passportExpiryDate
   * @return passportExpiryDate
  **/

  public LocalDate getPassportExpiryDate() {
    return passportExpiryDate;
  }

  public void setPassportExpiryDate(LocalDate passportExpiryDate) {
    this.passportExpiryDate = passportExpiryDate;
  }

  public PersonType passportIssuePlaceEnglish(String passportIssuePlaceEnglish) {
    this.passportIssuePlaceEnglish = passportIssuePlaceEnglish;
    return this;
  }

   /**
   * Get passportIssuePlaceEnglish
   * @return passportIssuePlaceEnglish
  **/

  public String getPassportIssuePlaceEnglish() {
    return passportIssuePlaceEnglish;
  }

  public void setPassportIssuePlaceEnglish(String passportIssuePlaceEnglish) {
    this.passportIssuePlaceEnglish = passportIssuePlaceEnglish;
  }

  public PersonType passportIssuePlaceArabic(String passportIssuePlaceArabic) {
    this.passportIssuePlaceArabic = passportIssuePlaceArabic;
    return this;
  }

   /**
   * Get passportIssuePlaceArabic
   * @return passportIssuePlaceArabic
  **/

  public String getPassportIssuePlaceArabic() {
    return passportIssuePlaceArabic;
  }

  public void setPassportIssuePlaceArabic(String passportIssuePlaceArabic) {
    this.passportIssuePlaceArabic = passportIssuePlaceArabic;
  }

  public PersonType passportIssueCountry(String passportIssueCountry) {
    this.passportIssueCountry = passportIssueCountry;
    return this;
  }

   /**
   * Get passportIssueCountry
   * @return passportIssueCountry
  **/

  public String getPassportIssueCountry() {
    return passportIssueCountry;
  }

  public void setPassportIssueCountry(String passportIssueCountry) {
    this.passportIssueCountry = passportIssueCountry;
  }

  public PersonType birthPlaceEnglish(String birthPlaceEnglish) {
    this.birthPlaceEnglish = birthPlaceEnglish;
    return this;
  }

   /**
   * Get birthPlaceEnglish
   * @return birthPlaceEnglish
  **/

  public String getBirthPlaceEnglish() {
    return birthPlaceEnglish;
  }

  public void setBirthPlaceEnglish(String birthPlaceEnglish) {
    this.birthPlaceEnglish = birthPlaceEnglish;
  }

  public PersonType birthPlaceArabic(String birthPlaceArabic) {
    this.birthPlaceArabic = birthPlaceArabic;
    return this;
  }

   /**
   * Get birthPlaceArabic
   * @return birthPlaceArabic
  **/

  public String getBirthPlaceArabic() {
    return birthPlaceArabic;
  }

  public void setBirthPlaceArabic(String birthPlaceArabic) {
    this.birthPlaceArabic = birthPlaceArabic;
  }

  public PersonType birthCountry(String birthCountry) {
    this.birthCountry = birthCountry;
    return this;
  }

   /**
   * Get birthCountry
   * @return birthCountry
  **/

  public String getBirthCountry() {
    return birthCountry;
  }

  public void setBirthCountry(String birthCountry) {
    this.birthCountry = birthCountry;
  }

  public PersonType decreeNumber(String decreeNumber) {
    this.decreeNumber = decreeNumber;
    return this;
  }

   /**
   * Get decreeNumber
   * @return decreeNumber
  **/

  public String getDecreeNumber() {
    return decreeNumber;
  }

  public void setDecreeNumber(String decreeNumber) {
    this.decreeNumber = decreeNumber;
  }

  public PersonType arabicName(String arabicName) {
    this.arabicName = arabicName;
    return this;
  }

   /**
   * Get arabicName
   * @return arabicName
  **/

  public String getArabicName() {
    return arabicName;
  }

  public void setArabicName(String arabicName) {
    this.arabicName = arabicName;
  }

  public PersonType englishName(String englishName) {
    this.englishName = englishName;
    return this;
  }

   /**
   * Get englishName
   * @return englishName
  **/

  public String getEnglishName() {
    return englishName;
  }

  public void setEnglishName(String englishName) {
    this.englishName = englishName;
  }

  public PersonType email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public PersonType mobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Get mobile
   * @return mobile
  **/

  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public PersonType status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/

  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public PersonType statusReason(Integer statusReason) {
    this.statusReason = statusReason;
    return this;
  }

   /**
   * Get statusReason
   * @return statusReason
  **/

  public Integer getStatusReason() {
    return statusReason;
  }

  public void setStatusReason(Integer statusReason) {
    this.statusReason = statusReason;
  }

  public PersonType activePerson(String activePerson) {
    this.activePerson = activePerson;
    return this;
  }

   /**
   * Get activePerson
   * @return activePerson
  **/

  public String getActivePerson() {
    return activePerson;
  }

  public void setActivePerson(String activePerson) {
    this.activePerson = activePerson;
  }

  public PersonType nationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

   /**
   * Get nationality
   * @return nationality
  **/

  public String getNationality() {
    return nationality;
  }

  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  public PersonType languagePreference(Integer languagePreference) {
    this.languagePreference = languagePreference;
    return this;
  }

   /**
   * Get languagePreference
   * @return languagePreference
  **/

  public Integer getLanguagePreference() {
    return languagePreference;
  }

  public void setLanguagePreference(Integer languagePreference) {
    this.languagePreference = languagePreference;
  }

  public PersonType fileNumber(String fileNumber) {
    this.fileNumber = fileNumber;
    return this;
  }

   /**
   * Get fileNumber
   * @return fileNumber
  **/

  public String getFileNumber() {
    return fileNumber;
  }

  public void setFileNumber(String fileNumber) {
    this.fileNumber = fileNumber;
  }

  public PersonType gcCuid(String gcCuid) {
    this.gcCuid = gcCuid;
    return this;
  }

   /**
   * Get gcCuid
   * @return gcCuid
  **/

  public String getGcCuid() {
    return gcCuid;
  }

  public void setGcCuid(String gcCuid) {
    this.gcCuid = gcCuid;
  }

  public PersonType familyBookNumber(String familyBookNumber) {
    this.familyBookNumber = familyBookNumber;
    return this;
  }

   /**
   * Get familyBookNumber
   * @return familyBookNumber
  **/

  public String getFamilyBookNumber() {
    return familyBookNumber;
  }

  public void setFamilyBookNumber(String familyBookNumber) {
    this.familyBookNumber = familyBookNumber;
  }

  public PersonType isVerifiedContact(Boolean isVerifiedContact) {
    this.isVerifiedContact = isVerifiedContact;
    return this;
  }

   /**
   * Get isVerifiedContact
   * @return isVerifiedContact
  **/

  public Boolean isIsVerifiedContact() {
    return isVerifiedContact;
  }

  public void setIsVerifiedContact(Boolean isVerifiedContact) {
    this.isVerifiedContact = isVerifiedContact;
  }

  public PersonType lastUpdatedBy(Integer lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * Get lastUpdatedBy
   * @return lastUpdatedBy
  **/

  public Integer getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(Integer lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public PersonType isMobileVerified(Boolean isMobileVerified) {
    this.isMobileVerified = isMobileVerified;
    return this;
  }

   /**
   * Get isMobileVerified
   * @return isMobileVerified
  **/

  public Boolean isIsMobileVerified() {
    return isMobileVerified;
  }

  public void setIsMobileVerified(Boolean isMobileVerified) {
    this.isMobileVerified = isMobileVerified;
  }

  public PersonType mobileVerificationDate(OffsetDateTime mobileVerificationDate) {
    this.mobileVerificationDate = mobileVerificationDate;
    return this;
  }

   /**
   * Get mobileVerificationDate
   * @return mobileVerificationDate
  **/

  public OffsetDateTime getMobileVerificationDate() {
    return mobileVerificationDate;
  }

  public void setMobileVerificationDate(OffsetDateTime mobileVerificationDate) {
    this.mobileVerificationDate = mobileVerificationDate;
  }

  public PersonType mobileVerificationChannel(Integer mobileVerificationChannel) {
    this.mobileVerificationChannel = mobileVerificationChannel;
    return this;
  }

   /**
   * Get mobileVerificationChannel
   * @return mobileVerificationChannel
  **/

  public Integer getMobileVerificationChannel() {
    return mobileVerificationChannel;
  }

  public void setMobileVerificationChannel(Integer mobileVerificationChannel) {
    this.mobileVerificationChannel = mobileVerificationChannel;
  }

  public PersonType isEmailVerified(Boolean isEmailVerified) {
    this.isEmailVerified = isEmailVerified;
    return this;
  }

   /**
   * Get isEmailVerified
   * @return isEmailVerified
  **/

  public Boolean isIsEmailVerified() {
    return isEmailVerified;
  }

  public void setIsEmailVerified(Boolean isEmailVerified) {
    this.isEmailVerified = isEmailVerified;
  }

  public PersonType emailVerificationDate(OffsetDateTime emailVerificationDate) {
    this.emailVerificationDate = emailVerificationDate;
    return this;
  }

   /**
   * Get emailVerificationDate
   * @return emailVerificationDate
  **/

  public OffsetDateTime getEmailVerificationDate() {
    return emailVerificationDate;
  }

  public void setEmailVerificationDate(OffsetDateTime emailVerificationDate) {
    this.emailVerificationDate = emailVerificationDate;
  }

  public PersonType emailVerificationChannel(Integer emailVerificationChannel) {
    this.emailVerificationChannel = emailVerificationChannel;
    return this;
  }

   /**
   * Get emailVerificationChannel
   * @return emailVerificationChannel
  **/

  public Integer getEmailVerificationChannel() {
    return emailVerificationChannel;
  }

  public void setEmailVerificationChannel(Integer emailVerificationChannel) {
    this.emailVerificationChannel = emailVerificationChannel;
  }

  public PersonType isScreened(Boolean isScreened) {
    this.isScreened = isScreened;
    return this;
  }

   /**
   * Get isScreened
   * @return isScreened
  **/

  public Boolean isIsScreened() {
    return isScreened;
  }

  public void setIsScreened(Boolean isScreened) {
    this.isScreened = isScreened;
  }

  public PersonType screeningDate(OffsetDateTime screeningDate) {
    this.screeningDate = screeningDate;
    return this;
  }

   /**
   * Get screeningDate
   * @return screeningDate
  **/

  public OffsetDateTime getScreeningDate() {
    return screeningDate;
  }

  public void setScreeningDate(OffsetDateTime screeningDate) {
    this.screeningDate = screeningDate;
  }

  public PersonType screeningChannel(Integer screeningChannel) {
    this.screeningChannel = screeningChannel;
    return this;
  }

   /**
   * Get screeningChannel
   * @return screeningChannel
  **/

  public Integer getScreeningChannel() {
    return screeningChannel;
  }

  public void setScreeningChannel(Integer screeningChannel) {
    this.screeningChannel = screeningChannel;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonType personType = (PersonType) o;
    return Objects.equals(this.personIssueAuthorityID, personType.personIssueAuthorityID) &&
        Objects.equals(this.birthDate, personType.birthDate) &&
        Objects.equals(this.gender, personType.gender) &&
        Objects.equals(this.unifiedID, personType.unifiedID) &&
        Objects.equals(this.emiratesID, personType.emiratesID) &&
        Objects.equals(this.emiratesIDIssueDate, personType.emiratesIDIssueDate) &&
        Objects.equals(this.emiratesIDExpiryDate, personType.emiratesIDExpiryDate) &&
        Objects.equals(this.passportNumber, personType.passportNumber) &&
        Objects.equals(this.passportIssueDate, personType.passportIssueDate) &&
        Objects.equals(this.passportExpiryDate, personType.passportExpiryDate) &&
        Objects.equals(this.passportIssuePlaceEnglish, personType.passportIssuePlaceEnglish) &&
        Objects.equals(this.passportIssuePlaceArabic, personType.passportIssuePlaceArabic) &&
        Objects.equals(this.passportIssueCountry, personType.passportIssueCountry) &&
        Objects.equals(this.birthPlaceEnglish, personType.birthPlaceEnglish) &&
        Objects.equals(this.birthPlaceArabic, personType.birthPlaceArabic) &&
        Objects.equals(this.birthCountry, personType.birthCountry) &&
        Objects.equals(this.decreeNumber, personType.decreeNumber) &&
        Objects.equals(this.arabicName, personType.arabicName) &&
        Objects.equals(this.englishName, personType.englishName) &&
        Objects.equals(this.email, personType.email) &&
        Objects.equals(this.mobile, personType.mobile) &&
        Objects.equals(this.status, personType.status) &&
        Objects.equals(this.statusReason, personType.statusReason) &&
        Objects.equals(this.activePerson, personType.activePerson) &&
        Objects.equals(this.nationality, personType.nationality) &&
        Objects.equals(this.languagePreference, personType.languagePreference) &&
        Objects.equals(this.fileNumber, personType.fileNumber) &&
        Objects.equals(this.gcCuid, personType.gcCuid) &&
        Objects.equals(this.familyBookNumber, personType.familyBookNumber) &&
        Objects.equals(this.isVerifiedContact, personType.isVerifiedContact) &&
        Objects.equals(this.lastUpdatedBy, personType.lastUpdatedBy) &&
        Objects.equals(this.isMobileVerified, personType.isMobileVerified) &&
        Objects.equals(this.mobileVerificationDate, personType.mobileVerificationDate) &&
        Objects.equals(this.mobileVerificationChannel, personType.mobileVerificationChannel) &&
        Objects.equals(this.isEmailVerified, personType.isEmailVerified) &&
        Objects.equals(this.emailVerificationDate, personType.emailVerificationDate) &&
        Objects.equals(this.emailVerificationChannel, personType.emailVerificationChannel) &&
        Objects.equals(this.isScreened, personType.isScreened) &&
        Objects.equals(this.screeningDate, personType.screeningDate) &&
        Objects.equals(this.screeningChannel, personType.screeningChannel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personIssueAuthorityID, birthDate, gender, unifiedID, emiratesID, emiratesIDIssueDate, emiratesIDExpiryDate, passportNumber, passportIssueDate, passportExpiryDate, passportIssuePlaceEnglish, passportIssuePlaceArabic, passportIssueCountry, birthPlaceEnglish, birthPlaceArabic, birthCountry, decreeNumber, arabicName, englishName, email, mobile, status, statusReason, activePerson, nationality, languagePreference, fileNumber, gcCuid, familyBookNumber, isVerifiedContact, lastUpdatedBy, isMobileVerified, mobileVerificationDate, mobileVerificationChannel, isEmailVerified, emailVerificationDate, emailVerificationChannel, isScreened, screeningDate, screeningChannel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonType {\n");
    
    sb.append("    personIssueAuthorityID: ").append(toIndentedString(personIssueAuthorityID)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    unifiedID: ").append(toIndentedString(unifiedID)).append("\n");
    sb.append("    emiratesID: ").append(toIndentedString(emiratesID)).append("\n");
    sb.append("    emiratesIDIssueDate: ").append(toIndentedString(emiratesIDIssueDate)).append("\n");
    sb.append("    emiratesIDExpiryDate: ").append(toIndentedString(emiratesIDExpiryDate)).append("\n");
    sb.append("    passportNumber: ").append(toIndentedString(passportNumber)).append("\n");
    sb.append("    passportIssueDate: ").append(toIndentedString(passportIssueDate)).append("\n");
    sb.append("    passportExpiryDate: ").append(toIndentedString(passportExpiryDate)).append("\n");
    sb.append("    passportIssuePlaceEnglish: ").append(toIndentedString(passportIssuePlaceEnglish)).append("\n");
    sb.append("    passportIssuePlaceArabic: ").append(toIndentedString(passportIssuePlaceArabic)).append("\n");
    sb.append("    passportIssueCountry: ").append(toIndentedString(passportIssueCountry)).append("\n");
    sb.append("    birthPlaceEnglish: ").append(toIndentedString(birthPlaceEnglish)).append("\n");
    sb.append("    birthPlaceArabic: ").append(toIndentedString(birthPlaceArabic)).append("\n");
    sb.append("    birthCountry: ").append(toIndentedString(birthCountry)).append("\n");
    sb.append("    decreeNumber: ").append(toIndentedString(decreeNumber)).append("\n");
    sb.append("    arabicName: ").append(toIndentedString(arabicName)).append("\n");
    sb.append("    englishName: ").append(toIndentedString(englishName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusReason: ").append(toIndentedString(statusReason)).append("\n");
    sb.append("    activePerson: ").append(toIndentedString(activePerson)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    languagePreference: ").append(toIndentedString(languagePreference)).append("\n");
    sb.append("    fileNumber: ").append(toIndentedString(fileNumber)).append("\n");
    sb.append("    gcCuid: ").append(toIndentedString(gcCuid)).append("\n");
    sb.append("    familyBookNumber: ").append(toIndentedString(familyBookNumber)).append("\n");
    sb.append("    isVerifiedContact: ").append(toIndentedString(isVerifiedContact)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    isMobileVerified: ").append(toIndentedString(isMobileVerified)).append("\n");
    sb.append("    mobileVerificationDate: ").append(toIndentedString(mobileVerificationDate)).append("\n");
    sb.append("    mobileVerificationChannel: ").append(toIndentedString(mobileVerificationChannel)).append("\n");
    sb.append("    isEmailVerified: ").append(toIndentedString(isEmailVerified)).append("\n");
    sb.append("    emailVerificationDate: ").append(toIndentedString(emailVerificationDate)).append("\n");
    sb.append("    emailVerificationChannel: ").append(toIndentedString(emailVerificationChannel)).append("\n");
    sb.append("    isScreened: ").append(toIndentedString(isScreened)).append("\n");
    sb.append("    screeningDate: ").append(toIndentedString(screeningDate)).append("\n");
    sb.append("    screeningChannel: ").append(toIndentedString(screeningChannel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
