/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * UBODeclarationType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class UBODeclarationType {
  @JsonProperty("companyIssueAuthorityID")
  private String companyIssueAuthorityID = null;

  @JsonProperty("mobile")
  private String mobile = null;

  @JsonProperty("channel")
  private Integer channel = null;

  @JsonProperty("notificationDate")
  private OffsetDateTime notificationDate = null;

  @JsonProperty("declarationDate")
  private OffsetDateTime declarationDate = null;

  @JsonProperty("isExemptIncomeSourceCheck")
  private Boolean isExemptIncomeSourceCheck = null;

  @JsonProperty("isExemptPEPDeclaration")
  private Boolean isExemptPEPDeclaration = null;

  @JsonProperty("UBOs")
  private List<UBOs> ubOs = null;

  public UBODeclarationType companyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
    return this;
  }

   /**
   * Get companyIssueAuthorityID
   * @return companyIssueAuthorityID
  **/

  public String getCompanyIssueAuthorityID() {
    return companyIssueAuthorityID;
  }

  public void setCompanyIssueAuthorityID(String companyIssueAuthorityID) {
    this.companyIssueAuthorityID = companyIssueAuthorityID;
  }

  public UBODeclarationType mobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Get mobile
   * @return mobile
  **/

  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public UBODeclarationType channel(Integer channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/

  public Integer getChannel() {
    return channel;
  }

  public void setChannel(Integer channel) {
    this.channel = channel;
  }

  public UBODeclarationType notificationDate(OffsetDateTime notificationDate) {
    this.notificationDate = notificationDate;
    return this;
  }

   /**
   * Get notificationDate
   * @return notificationDate
  **/

  public OffsetDateTime getNotificationDate() {
    return notificationDate;
  }

  public void setNotificationDate(OffsetDateTime notificationDate) {
    this.notificationDate = notificationDate;
  }

  public UBODeclarationType declarationDate(OffsetDateTime declarationDate) {
    this.declarationDate = declarationDate;
    return this;
  }

   /**
   * Get declarationDate
   * @return declarationDate
  **/

  public OffsetDateTime getDeclarationDate() {
    return declarationDate;
  }

  public void setDeclarationDate(OffsetDateTime declarationDate) {
    this.declarationDate = declarationDate;
  }

  public UBODeclarationType isExemptIncomeSourceCheck(Boolean isExemptIncomeSourceCheck) {
    this.isExemptIncomeSourceCheck = isExemptIncomeSourceCheck;
    return this;
  }

   /**
   * Get isExemptIncomeSourceCheck
   * @return isExemptIncomeSourceCheck
  **/

  public Boolean isIsExemptIncomeSourceCheck() {
    return isExemptIncomeSourceCheck;
  }

  public void setIsExemptIncomeSourceCheck(Boolean isExemptIncomeSourceCheck) {
    this.isExemptIncomeSourceCheck = isExemptIncomeSourceCheck;
  }

  public UBODeclarationType isExemptPEPDeclaration(Boolean isExemptPEPDeclaration) {
    this.isExemptPEPDeclaration = isExemptPEPDeclaration;
    return this;
  }

   /**
   * Get isExemptPEPDeclaration
   * @return isExemptPEPDeclaration
  **/

  public Boolean isIsExemptPEPDeclaration() {
    return isExemptPEPDeclaration;
  }

  public void setIsExemptPEPDeclaration(Boolean isExemptPEPDeclaration) {
    this.isExemptPEPDeclaration = isExemptPEPDeclaration;
  }

  public UBODeclarationType ubOs(List<UBOs> ubOs) {
    this.ubOs = ubOs;
    return this;
  }

  public UBODeclarationType addUbOsItem(UBOs ubOsItem) {
    if (this.ubOs == null) {
      this.ubOs = new ArrayList<>();
    }
    this.ubOs.add(ubOsItem);
    return this;
  }

   /**
   * Get ubOs
   * @return ubOs
  **/

  public List<UBOs> getUbOs() {
    return ubOs;
  }

  public void setUbOs(List<UBOs> ubOs) {
    this.ubOs = ubOs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UBODeclarationType ubODeclarationType = (UBODeclarationType) o;
    return Objects.equals(this.companyIssueAuthorityID, ubODeclarationType.companyIssueAuthorityID) &&
        Objects.equals(this.mobile, ubODeclarationType.mobile) &&
        Objects.equals(this.channel, ubODeclarationType.channel) &&
        Objects.equals(this.notificationDate, ubODeclarationType.notificationDate) &&
        Objects.equals(this.declarationDate, ubODeclarationType.declarationDate) &&
        Objects.equals(this.isExemptIncomeSourceCheck, ubODeclarationType.isExemptIncomeSourceCheck) &&
        Objects.equals(this.isExemptPEPDeclaration, ubODeclarationType.isExemptPEPDeclaration) &&
        Objects.equals(this.ubOs, ubODeclarationType.ubOs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyIssueAuthorityID, mobile, channel, notificationDate, declarationDate, isExemptIncomeSourceCheck, isExemptPEPDeclaration, ubOs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UBODeclarationType {\n");
    
    sb.append("    companyIssueAuthorityID: ").append(toIndentedString(companyIssueAuthorityID)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    notificationDate: ").append(toIndentedString(notificationDate)).append("\n");
    sb.append("    declarationDate: ").append(toIndentedString(declarationDate)).append("\n");
    sb.append("    isExemptIncomeSourceCheck: ").append(toIndentedString(isExemptIncomeSourceCheck)).append("\n");
    sb.append("    isExemptPEPDeclaration: ").append(toIndentedString(isExemptPEPDeclaration)).append("\n");
    sb.append("    ubOs: ").append(toIndentedString(ubOs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
