/*
 * DBNDataInMotionAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.exceltodb.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * UBOs
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-18T11:35:52.868958+04:00[Asia/Dubai]")

public class UBOs {
  @JsonProperty("issueAuthorityID")
  private String issueAuthorityID = null;

  @JsonProperty("legalEntity")
  private LegalEntityType legalEntity = null;

  @JsonProperty("addDate")
  private LocalDate addDate = null;

  @JsonProperty("isPEP")
  private Boolean isPEP = null;

  @JsonProperty("PEPProfile")
  private Integer pePProfile = null;

  @JsonProperty("PEPDetails")
  private String pePDetails = null;

  @JsonProperty("incomeSources")
  private List<IncomeSources> incomeSources = null;

  @JsonProperty("incomeCountries")
  private List<IncomeCountries> incomeCountries = null;

  public UBOs issueAuthorityID(String issueAuthorityID) {
    this.issueAuthorityID = issueAuthorityID;
    return this;
  }

   /**
   * Get issueAuthorityID
   * @return issueAuthorityID
  **/

  public String getIssueAuthorityID() {
    return issueAuthorityID;
  }

  public void setIssueAuthorityID(String issueAuthorityID) {
    this.issueAuthorityID = issueAuthorityID;
  }

  public UBOs legalEntity(LegalEntityType legalEntity) {
    this.legalEntity = legalEntity;
    return this;
  }

   /**
   * Get legalEntity
   * @return legalEntity
  **/

  public LegalEntityType getLegalEntity() {
    return legalEntity;
  }

  public void setLegalEntity(LegalEntityType legalEntity) {
    this.legalEntity = legalEntity;
  }

  public UBOs addDate(LocalDate addDate) {
    this.addDate = addDate;
    return this;
  }

   /**
   * Get addDate
   * @return addDate
  **/

  public LocalDate getAddDate() {
    return addDate;
  }

  public void setAddDate(LocalDate addDate) {
    this.addDate = addDate;
  }

  public UBOs isPEP(Boolean isPEP) {
    this.isPEP = isPEP;
    return this;
  }

   /**
   * Get isPEP
   * @return isPEP
  **/

  public Boolean isIsPEP() {
    return isPEP;
  }

  public void setIsPEP(Boolean isPEP) {
    this.isPEP = isPEP;
  }

  public UBOs pePProfile(Integer pePProfile) {
    this.pePProfile = pePProfile;
    return this;
  }

   /**
   * Get pePProfile
   * @return pePProfile
  **/

  public Integer getPePProfile() {
    return pePProfile;
  }

  public void setPePProfile(Integer pePProfile) {
    this.pePProfile = pePProfile;
  }

  public UBOs pePDetails(String pePDetails) {
    this.pePDetails = pePDetails;
    return this;
  }

   /**
   * Get pePDetails
   * @return pePDetails
  **/

  public String getPePDetails() {
    return pePDetails;
  }

  public void setPePDetails(String pePDetails) {
    this.pePDetails = pePDetails;
  }

  public UBOs incomeSources(List<IncomeSources> incomeSources) {
    this.incomeSources = incomeSources;
    return this;
  }

  public UBOs addIncomeSourcesItem(IncomeSources incomeSourcesItem) {
    if (this.incomeSources == null) {
      this.incomeSources = new ArrayList<>();
    }
    this.incomeSources.add(incomeSourcesItem);
    return this;
  }

   /**
   * Get incomeSources
   * @return incomeSources
  **/

  public List<IncomeSources> getIncomeSources() {
    return incomeSources;
  }

  public void setIncomeSources(List<IncomeSources> incomeSources) {
    this.incomeSources = incomeSources;
  }

  public UBOs incomeCountries(List<IncomeCountries> incomeCountries) {
    this.incomeCountries = incomeCountries;
    return this;
  }

  public UBOs addIncomeCountriesItem(IncomeCountries incomeCountriesItem) {
    if (this.incomeCountries == null) {
      this.incomeCountries = new ArrayList<>();
    }
    this.incomeCountries.add(incomeCountriesItem);
    return this;
  }

   /**
   * Get incomeCountries
   * @return incomeCountries
  **/

  public List<IncomeCountries> getIncomeCountries() {
    return incomeCountries;
  }

  public void setIncomeCountries(List<IncomeCountries> incomeCountries) {
    this.incomeCountries = incomeCountries;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UBOs ubOs = (UBOs) o;
    return Objects.equals(this.issueAuthorityID, ubOs.issueAuthorityID) &&
        Objects.equals(this.legalEntity, ubOs.legalEntity) &&
        Objects.equals(this.addDate, ubOs.addDate) &&
        Objects.equals(this.isPEP, ubOs.isPEP) &&
        Objects.equals(this.pePProfile, ubOs.pePProfile) &&
        Objects.equals(this.pePDetails, ubOs.pePDetails) &&
        Objects.equals(this.incomeSources, ubOs.incomeSources) &&
        Objects.equals(this.incomeCountries, ubOs.incomeCountries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issueAuthorityID, legalEntity, addDate, isPEP, pePProfile, pePDetails, incomeSources, incomeCountries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UBOs {\n");
    
    sb.append("    issueAuthorityID: ").append(toIndentedString(issueAuthorityID)).append("\n");
    sb.append("    legalEntity: ").append(toIndentedString(legalEntity)).append("\n");
    sb.append("    addDate: ").append(toIndentedString(addDate)).append("\n");
    sb.append("    isPEP: ").append(toIndentedString(isPEP)).append("\n");
    sb.append("    pePProfile: ").append(toIndentedString(pePProfile)).append("\n");
    sb.append("    pePDetails: ").append(toIndentedString(pePDetails)).append("\n");
    sb.append("    incomeSources: ").append(toIndentedString(incomeSources)).append("\n");
    sb.append("    incomeCountries: ").append(toIndentedString(incomeCountries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
